export type Phase='Lancement'|'Phase 2'|'Phase 3'|'Long terme';
export type Spec={id:number;title:string;path:string;group:string;phase:Phase;deps:string[];features:Partial<Record<Phase,string[]>>};
const S=(id:number,title:string,path:string,group:string,phase:Phase,deps:string[],launch:string,second='',third='',long=''):Spec=>({id,title,path,group,phase,deps,features:{Lancement:launch?launch.split('|'):[], 'Phase 2':second?second.split('|'):[],'Phase 3':third?third.split('|'):[],'Long terme':long?long.split('|'):[]}});
export const specs:Spec[]=[
S(47,'Annonces de l’accueil','/admin/annonces','Administration','Lancement',['Identité','Base de données','Contenus'],'Créer et modifier des annonces|Programmer les publications|Épingler à la une|Archiver|Associer vidéos, sorties, articles et presse'),
S(46,'Participer à ERPI','/participer','Participer','Lancement',['Événements','Formations'],'Choisir une sortie ou une formation|Accès aux ressources et à la communauté|Offres pour les groupes'),
S(1,'Accueil','/','Découvrir','Lancement',['Contenus','Enquêtes','Événements'],'Présentation et mission|Accès signalement, participation, dossiers, événements et boutique|Prochaine enquête publique|Dernier dossier et dernière vidéo|Nicolas Vora et équipe|Newsletter et réseaux sociaux','Produits et kits mis en avant|Chiffres clés vérifiés|Avis autorisés|Médias et reportages'),
S(2,'ERPI Paranormal','/erpi','Découvrir','Lancement',['Contenus'],'Histoire et présentation de Nicolas Vora|Équipe|Philosophie, valeurs et positionnement|Méthode d’investigation|Matériel utilisé|FAQ ERPI','Historique des enquêtes|Chronologie|Presse, TV et interviews|Partenaires'),
S(3,'Dossiers d’enquête','/dossiers','Enquêter','Lancement',['Enquêtes','Recherche'],'Cartes des enquêtes|Recherche|Filtres date, région, lieu, phénomène et statut|Tri récent et ancien|Accès au dossier|Pagination','Filtre équipe|Tris plus consulté et plus commenté'),
S(4,'Dossier d’enquête','/dossiers/maison-ancienne','Enquêter','Lancement',['Enquêtes','Médias','Confidentialité'],'Numéro, nom, date, lieu, région, type et statut|Contexte, témoignages initiaux et phénomènes rapportés|Équipe et matériel|Chronologie|Photos, vidéos, audios et EVP|Données et mesures|Hypothèses, explications rationnelles, éléments inexpliqués et conclusion|Vidéo YouTube et articles associés|Partage et dossiers similaires','Produits utilisés|Commentaires et réactions modérés'),
S(5,'Carte des enquêtes','/carte','Enquêter','Phase 2',['Enquêtes','Événements','Géolocalisation'],'','Carte interactive|Points enquêtes et événements futurs|Filtres région, statut et phénomène|Recherche ville et région|Catégories de points|Aperçu et lien dossier','Lieux partenaires'),
S(6,'Signaler un phénomène','/signaler','Enquêter','Lancement',['Signalements','Fichiers privés','Notifications','Identité'],'Explication et formulaire progressif|Coordonnées du témoin, adresse et type de bâtiment|Début, fréquence et nombre de témoins|Description et phénomènes observés|Sons, ombres, lumières, objets, sensations, odeurs, électricité et animaux|Personnes présentes et historique connu|Photos, vidéos, audio et documents|Contact, diffusion facultative et conditions distinctes|Numéro automatique et confirmation|Invitation sécurisée à l’espace personnel|Suivi et pièces complémentaires'),
S(7,'Suivi de mon dossier','/compte/dossiers','Mon espace','Lancement',['Signalements','Identité','Fichiers privés'],'Accès privé|Numéro, statut et dernière mise à jour|Messages ERPI et compléments|Ajout de photos, vidéos, audio et documents|Historique|Rendez-vous|Rapport final téléchargeable|Clôture de la demande'),
S(8,'Interventions chez les particuliers','/interventions','Enquêter','Lancement',['Contenus','Signalements'],'Analyse des demandes et étapes avant déplacement|Conditions et zones d’intervention|Tarifs ou frais à confirmer|Confidentialité, droit à l’image et sécurité|Ce qu’ERPI fait et ne fait pas|FAQ|Soumettre mon cas'),
S(9,'Rendez-vous / visio','/rendez-vous','Enquêter','Phase 2',['Calendrier','Signalements','Notifications'],'','Disponibilités|Type : analyse visio, téléphone, entretien avant intervention|Date et heure|Formulaire préalable|Confirmation et rappels|Annulation et report|Lien de visioconférence'),
S(10,'Événements','/evenements','Participer','Lancement',['Événements'],'Prochains événements et archives|Filtres région et type|Places, prix, date, durée, niveau, âge et lieu|Réserver','Carte|Liste d’attente|Galeries des événements passés'),
S(11,'Détail d’un événement','/evenements/nuit-decouverte','Participer','Lancement',['Événements','Billetterie'],'Nom, description, photos et vidéo|Histoire du lieu|Date, début, fin, adresse et carte|Capacité, places restantes, tarif et âge minimum|Matériel fourni et conseillé|Niveau physique, consignes et FAQ|Annulation et droit à l’image|Réserver et partager','Liste d’attente|Événements similaires'),
S(12,'Réservation / billetterie','/reservation/nuit-decouverte','Participer','Lancement',['Billetterie','Paiements','Identité','Notifications'],'Nombre et informations des participants|Paiement|Conditions générales et règlement|Confirmation|Billet et QR code|Facture|Rappel automatique|Contrôle billet à l’entrée','Code promo|Ajout calendrier|Transfert encadré du billet'),
S(13,'Boutique','/boutique','Boutique','Phase 2',['Commerce','Stocks','Recherche'],'','Catalogue, recherche, filtres et catégories|Vedettes et nouveautés|Produits utilisés par ERPI|Kits et promotions|Panier, favoris et compte client'),
S(14,'Fiche produit','/boutique/detecteur-emf','Boutique','Phase 2',['Commerce','Stocks','Médias'],'','Photos et vidéos|Prix, stock, variantes et disponibilité|Description et caractéristiques|Fonction réelle, utilisation ERPI, limites et faux positifs|Tutoriel et notice|Compléments|Avis clients|Panier et favoris|Livraison estimée','Comparateur'),
S(15,'Kits ERPI','/kits','Boutique','Phase 2',['Commerce','Stocks','Formations'],'','Kits débutant, intermédiaire et avancé|Comparaison|Contenu et prix|Vidéo|Mini-formation offerte|Ajout au panier'),
S(16,'Formations','/formations','Apprendre','Phase 2',['Formations','Paiements'],'','Catalogue et filtres|Présentiel, en ligne et ateliers|Débutant et avancé|Groupes, associations et jeunes|Dates, prix, inscriptions|Avis et FAQ'),
S(17,'Détail d’une formation','/formations/premiere-enquete','Apprendre','Phase 2',['Formations','Billetterie','Droits d’accès'],'','Programme, objectifs, niveau et durée|Formateur et matériel|Date, lieu ou vidéos|Prix et capacité|Inscription|Documents et FAQ','Certificat de participation'),
S(18,'Académie / ressources','/academie','Apprendre','Lancement',['Contenus','Médias'],'Articles, guides et tutoriels gratuits|Vidéos|Lexique|Faux positifs|Matériel, sécurité et méthodologie|Analyse audio et vidéo|Dossiers pédagogiques','Ressources premium'),
S(19,'Matériel ERPI','/materiel','Apprendre','Lancement',['Contenus','Enquêtes'],'Matériel de l’équipe et fiches techniques|Pourquoi et comment l’utiliser|Enquêtes associées|Tutoriels et notes','Liens boutique|Comparatifs'),
S(20,'Médias','/medias','Découvrir','Lancement',['Contenus'],'TV, presse, radio, podcasts et interviews|Articles, vidéos et logos autorisés|Dates et liens sources|Contact presse','Kit presse téléchargeable'),
S(21,'Vidéos','/videos','Découvrir','Lancement',['Médias','Enquêtes'],'Intégrations YouTube|Enquêtes, matériel, shorts, interviews et lives|Recherche et filtres|Dossier associé'),
S(22,'Blog / actualités','/actualites','Découvrir','Lancement',['Contenus','Recherche'],'Articles|Enquêtes, produits, événements et coulisses|Actualités paranormales et interviews|Tags, catégories, recherche, SEO et articles associés'),
S(23,'Communauté','/communaute','Participer','Phase 3',['Abonnements','Droits d’accès','Modération'],'','','Présentation, avantages et niveaux d’abonnement|Contenus exclusifs, lives privés et coulisses|Accès anticipé événements|Réductions boutique|Votes|Discord ou espace communautaire|Inscription'),
S(24,'Espace membre','/membre','Mon espace','Phase 3',['Identité','Abonnements','Droits d’accès'],'','','Profil, abonnement et historique|Exclusivités, dossiers privés autorisés et lives|Remises|Billets, commandes et formations|Favoris, notifications et paramètres'),
S(25,'Mon compte','/compte','Mon espace','Lancement',['Identité'],'Informations personnelles et préférences|Dossiers signalés et billets|Newsletter et mot de passe|Suppression et demande d’export','Adresses, commandes et factures|Formations et favoris','Abonnement premium'),
S(26,'Partenaires','/partenaires','Professionnels','Phase 2',['Contenus','Contact'],'','Lieux, fabricants, boutiques, médias, associations et sponsors|Logos, présentations et liens|Devenir partenaire'),
S(27,'Pour les lieux / professionnels','/professionnels','Professionnels','Lancement',['Contenus','Contact'],'Offres B2B|Nuits d’enquête et animation de lieux historiques|Événements privés et team building|Création de contenu et mise en avant du lieu|Partenariats|Contact professionnel et devis','Exemples de réalisations|Dossier commercial'),
S(28,'Observatoire ERPI','/observatoire','Enquêter','Phase 3',['Signalements','Anonymisation','Statistiques'],'','','Dossiers reçus|Répartition géographique|Phénomènes et types de lieux|Taux expliqués et indéterminés|Graphiques et carte|Rapport annuel PDF|Archives par année'),
S(29,'FAQ','/faq','Aide','Lancement',['Contenus'],'ERPI, enquêtes, signalements, interventions et événements','Boutique, matériel, formations, paiements et livraison','Communauté'),
S(30,'Contact','/contact','Aide','Lancement',['Contact','Notifications'],'Formulaire général|Motif et routage presse, partenariat, professionnel, boutique et événement|Email et réseaux officiels vérifiés'),
S(31,'Newsletter','/newsletter','Aide','Lancement',['Consentements','Notifications'],'Inscription|Confirmation email|Consentement et désinscription','Choix des thèmes','Archives publiques facultatives'),
S(32,'Panier','/panier','Boutique','Phase 2',['Commerce','Stocks'],'','Produits et quantités|Suppression|Code promo|Estimation livraison|Total et passage commande'),
S(33,'Commande / checkout','/commande','Boutique','Phase 2',['Commerce','Paiements','Livraison'],'','Adresse, livraison et facturation|Paiement|CGV|Récapitulatif et confirmation'),
S(34,'Confirmation de commande','/commande/confirmation','Boutique','Phase 2',['Commerce','Notifications','Identité'],'','Numéro, résumé et facture|Suivi livraison|Produits associés|Invitation compte après achat invité'),
S(35,'Recherche','/recherche','Aide','Lancement',['Recherche','Contenus'],'Recherche dossiers, articles, événements, vidéos et pages|Filtres par type','Produits et formations'),
S(36,'Page introuvable','/404','Aide','Lancement',['Recherche'],'Message 404|Recherche|Retour accueil|Dossiers et vidéos suggérés'),
S(37,'Pages légales','/legal','Aide','Lancement',['Consentements','Confidentialité'],'Mentions légales, confidentialité et cookies|CGU|Conditions interventions|Droit à l’image|Annulation événements et remboursements applicables','CGV boutique et formations|Livraison|Retours|Remboursements commerciaux'),
S(38,'Administration','/admin/contenus','Administration','Lancement',['Identité','Rôles','Journal'],'Gestion sans code : dossiers, signalements, utilisateurs|Événements, réservations et billets|Médias, vidéos, articles et pages|Messages, newsletter, statistiques et SEO','Produits, stocks, commandes, promotions et fournisseurs|Formations, partenaires et avis'),
S(39,'Tableau de bord admin','/admin','Administration','Lancement',['Statistiques','Signalements','Billetterie'],'Visiteurs, inscriptions, signalements et dossiers actifs|Événements à venir, billets vendus et remplissage|CA événements|Pages et vidéos principales|Sources trafic et conversion','CA boutique, panier moyen, commandes et stocks faibles|CA formations','Abonnements'),
S(40,'Notifications','/admin/notifications','Administration','Lancement',['Notifications','Consentements'],'Confirmations, rappels, changement de statut|Événement prochain et billet disponible|Notifications internes admin|Newsletter','Commande expédiée|Nouvelle formation|Retour produit en stock'),
S(41,'Automatisations','/admin/automatisations','Administration','Lancement',['Notifications','Tâches planifiées'],'Numéro dossier et billet automatiques|Emails post-réservation|Invitation client à son espace|Rappel événement|Alerte nouveau signalement prioritaire','Panier abandonné selon éligibilité|Avis post-événement et post-commande|Liste d’attente'),
S(42,'Analytics','/admin/analytics','Administration','Lancement',['Statistiques','Consentements'],'Trafic, sources, pages vues, clics et vidéos|Formulaires commencés et terminés|Réservations et conversion|Remplissage|Newsletter','Panier, ventes, panier moyen et revenus par levier','Membres payants et rétention'),
S(43,'SEO','/admin/seo','Administration','Lancement',['Contenus','Recherche'],'URLs propres et métadonnées|Sitemap|Données structurées pertinentes|Dossiers, événements et articles|Images optimisées et partage réseaux','Produits|Pages locales avec contenu réel'),
S(44,'Sécurité / confidentialité','/admin/securite','Administration','Lancement',['Identité','Rôles','Sauvegardes'],'Consentements et bases de traitement documentés|Signalements sensibles et dossiers privés protégés|Rôles|Sauvegardes restaurables|Anti-spam et protection formulaires|Journal admin|Suppression / anonymisation sur demande'),
S(45,'Rôles utilisateurs','/admin/roles','Administration','Lancement',['Identité'],'Visiteur|Participant événement|Témoin déclarant|Enquêteur ERPI|Rédacteur|Administrateur','Client boutique|Responsable boutique','Membre premium')
];
export const statuses=['En préparation','Investigation prévue','En cours','Analyse en cours','Explication trouvée','Explication probable','Indéterminé','Classé'];
export const phenomena=['Sons','Ombres','Lumières','Déplacement d’objets','Sensations','Odeurs','Problèmes électriques','Animaux'];
export const productCategories=['Détecteurs EMF','K2','REM Pod','Spirit Box','Ghost Box','EVP','Enregistreurs','Caméras','IR / UV','Éclairage','Capteurs','Accessoires','Valises','Batteries','Kits ERPI','Livres','Carnets','Merchandising','Sélection ésotérique'];
export const eventTypes=['Nuit d’enquête','Soirée découverte','Enquête dans un château','Enquête dans un hôtel','Enquête dans un fort','Enquête privée','Team building','Conférence','Atelier','Salon','Rencontre abonnés'];
export type RecordItem={id:string;title:string;type:string;desc:string;region:string;date:string;status:string;price?:number;stock?:number;duration?:string;level?:string;phenomenon?:string;place?:string;views?:number;comments?:number;team?:string};
export const dossiers:RecordItem[]=[
{id:'maison-ancienne',title:'Bruits nocturnes dans une maison ancienne',type:'Maison',desc:'Un cas pédagogique pour comprendre comment distinguer les observations, les hypothèses et les conclusions.',region:'Grand Est',date:'2026-08-15',status:'Explication probable',phenomenon:'Sons',place:'Lieu fictif • adresse confidentielle',views:240,comments:3,team:'Équipe de démonstration'},
{id:'lumieres-fort',title:'Lumières inhabituelles dans un ancien fort',type:'Fort',desc:'Une enquête de démonstration consacrée aux reflets et aux sources lumineuses extérieures.',region:'Provence-Alpes-Côte d’Azur',date:'2026-07-21',status:'Analyse en cours',phenomenon:'Lumières',place:'Lieu fictif',views:160,comments:1,team:'Équipe de démonstration'},
{id:'ombres-chateau',title:'Ombres rapportées dans un château',type:'Château',desc:'Recueil des témoignages et préparation d’un protocole d’observation.',region:'Bourgogne-Franche-Comté',date:'2026-06-12',status:'En préparation',phenomenon:'Ombres',place:'Lieu fictif',views:80,comments:0,team:'Équipe de démonstration'},
{id:'mesures-hotel',title:'Variations électromagnétiques dans un hôtel',type:'Hôtel',desc:'Un exemple de comparaison des mesures avec les équipements électriques du bâtiment.',region:'Grand Est',date:'2026-05-05',status:'Explication trouvée',phenomenon:'Problèmes électriques',place:'Lieu fictif',views:310,comments:4,team:'Équipe de démonstration'}];
export const events:RecordItem[]=[
{id:'nuit-decouverte',title:'Une nuit pour découvrir l’investigation',type:'Nuit d’enquête',desc:'Un parcours d’exemple : présentation du protocole, prise en main du matériel et observation en petits groupes.',region:'Grand Est',date:'2026-10-24',status:'Réservation de démonstration',price:45,stock:12,duration:'4 heures',level:'Débutant',place:'Lieu de démonstration — aucune session annoncée'},
{id:'atelier-audio',title:'Écouter, analyser, comparer',type:'Atelier',desc:'Une séance pédagogique d’exemple autour des enregistrements et des faux positifs audio.',region:'En ligne',date:'2026-11-07',status:'Réservation de démonstration',price:25,stock:8,duration:'2 heures',level:'Tous niveaux',place:'Visioconférence de démonstration'},
{id:'chateau',title:'Investigation dans un lieu historique',type:'Enquête dans un château',desc:'Une session fictive pour essayer le parcours de liste d’attente.',region:'Bourgogne-Franche-Comté',date:'2026-11-21',status:'Complet',price:65,stock:0,duration:'5 heures',level:'Intermédiaire',place:'Lieu fictif'},
{id:'rencontre',title:'Rencontre autour des méthodes d’enquête',type:'Rencontre abonnés',desc:'Exemple d’archive d’un événement passé. Aucun compte rendu réel associé.',region:'Grand Est',date:'2026-05-10',status:'Passé',price:0,stock:0,duration:'2 heures',level:'Tous niveaux',place:'Lieu fictif'}];
export const products:RecordItem[]=[
{id:'detecteur-emf',title:'Détecteur de champ EMF',type:'Détecteurs EMF',desc:'Mesurer des variations de champ électromagnétique et les comparer aux sources environnantes.',region:'',date:'2026-09-01',status:'Disponible',price:49,stock:15},
{id:'enregistreur',title:'Enregistreur audio numérique',type:'Enregistreurs',desc:'Conserver une trace audio pour l’écouter, l’annoter et la confronter au contexte.',region:'',date:'2026-08-01',status:'Disponible',price:89,stock:6},
{id:'carnet',title:'Carnet d’investigation',type:'Carnets',desc:'Consigner les horaires, les conditions, les observations et les hypothèses.',region:'',date:'2026-07-01',status:'Disponible',price:15,stock:25},
{id:'kit-debutant',title:'Kit ERPI • découverte',type:'Kits ERPI',desc:'Détecteur EMF, carnet et guide de démarrage. ',region:'',date:'2026-09-01',status:'Disponible',price:59,stock:8},
{id:'kit-intermediaire',title:'Kit ERPI • terrain',type:'Kits ERPI',desc:'Détecteur EMF, enregistreur et carnet. ',region:'',date:'2026-09-01',status:'Disponible',price:139,stock:4},
{id:'kit-avance',title:'Kit ERPI • analyse',type:'Kits ERPI',desc:'Base terrain, capteur et accessoires de transport. ',region:'',date:'2026-09-01',status:'Disponible',price:219,stock:0}];
export const courses:RecordItem[]=[
{id:'premiere-enquete',title:'Préparer sa première enquête',type:'En ligne',desc:'De la prise de contact au compte rendu : construire un protocole d’observation.',region:'En ligne',date:'2026-11-01',status:'Programme de démonstration',price:39,stock:20,duration:'3 heures',level:'Débutant'},
{id:'analyse-audio',title:'Les bases de l’analyse audio',type:'Atelier',desc:'Conserver l’original, comparer les pistes et identifier les limites d’un enregistrement.',region:'Grand Est',date:'2026-11-15',status:'Programme de démonstration',price:59,stock:10,duration:'4 heures',level:'Avancé'}];
export const resources=[
{id:'methode',title:'Préparer une observation méthodique',type:'Méthodologie',intro:'Un bon dossier permet de distinguer ce qui a été observé de ce qui a été supposé.',sections:[['Consigner avant d’interpréter','Notez l’heure, le lieu, les personnes présentes et la durée. Décrivez les faits avec des termes précis, sans attribuer d’emblée une origine au phénomène.'],['Comparer les conditions','Relevez les sources de bruit et de lumière, les appareils électriques et les changements de conditions. Une différence de contexte peut expliquer une différence d’observation.'],['Documenter les limites','Indiquez ce qui n’a pas pu être vérifié. Un élément non expliqué ne suffit pas à établir une origine paranormale.']]},
{id:'faux-positifs',title:'Reconnaître les faux positifs',type:'Faux positifs',intro:'Un signal inhabituel mérite d’abord une vérification du contexte.',sections:[['Lumière et image','Un reflet, de la poussière proche de l’objectif ou un mouvement de caméra peuvent produire une image surprenante. Conservez les séquences avant et après le passage observé.'],['Bruits et enregistrements','Un frottement, une voix éloignée ou une compression audio peuvent modifier la perception. Comparez l’original et toute version traitée.'],['Mesures','Un appareil mesure une grandeur physique dans certaines limites. Une valeur inhabituelle doit être comparée aux sources locales et aux caractéristiques du capteur.']]},
{id:'audio',title:'Conserver et analyser un fichier audio',type:'Analyse audio',intro:'Une analyse reproductible commence par la conservation du fichier original.',sections:[['Conserver l’original','Travaillez sur une copie. Notez le matériel, les réglages et les conditions de captation.'],['Tracer les traitements','Documentez chaque filtre et chaque modification. Une transformation peut aussi créer des artefacts.'],['Écoute indépendante','Faites écouter l’extrait sans suggérer de mots. Comparez les interprétations plutôt que de présenter une seule lecture comme certaine.']]},
{id:'securite',title:'Préparer une sortie en sécurité',type:'Sécurité',intro:'Une investigation exige d’abord un lieu autorisé et des conditions maîtrisées.',sections:[['Autorisation du lieu','Vérifiez l’accord du responsable et les zones accessibles. Respectez toute zone fermée ou interdite.'],['Préparation du groupe','Identifiez les issues, les moyens de communication et la personne responsable. Vérifiez éclairage, batteries et conditions d’accès.'],['Arrêter si nécessaire','Interrompez la sortie si le lieu ou les conditions ne permettent plus de circuler sans danger.']]},
{id:'lexique',title:'Lexique de l’investigation',type:'Lexique',intro:'Des mots utiles pour lire un dossier avec précision.',sections:[['EVP','Abréviation de « Electronic Voice Phenomenon », employée pour désigner des sons interprétés comme des voix dans un enregistrement. Cette appellation ne démontre pas leur origine.'],['EMF','Champ électromagnétique. La mesure dépend du capteur, de la fréquence et du contexte.'],['Indéterminé','Conclusion employée lorsque les éléments disponibles ne permettent pas de retenir une explication suffisamment étayée.']]}
];
export const sourceLinks=[{title:'En quête de fantômes au château du Schwarzenbourg',publisher:'Dernières Nouvelles d’Alsace',date:'18 août 2021',url:'https://www.dna.fr/insolite/2021/08/18/grand-format-en-quete-de-fantomes-au-chateau-du-schwarzenbourg',desc:'Un reportage consacré à Nicolas Vora et à une sortie dans les ruines du Schwarzenbourg. Accès à l’article selon les conditions du média.'},{title:'Ghostbusters of the French Riviera',publisher:'HelloMonaco',date:'16 novembre 2016',url:'https://www.hellomonaco.com/the-riviera/ghostbusters-of-the-french-riviera/',desc:'Un article historique citant Nicolas Vora, Romain Gorlez et l’association ERPI Paranormal. Les informations de 2016 ne décrivent pas nécessairement l’activité actuelle.'}];
export const legalPages=['Mentions légales','Politique de confidentialité','Cookies','CGU','CGV','Politique de livraison','Retours','Annulation événements','Politique de remboursement','Droit à l’image','Conditions des interventions'];
export const slugify=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n);
