'use client';
import {useEffect,useRef,useState} from 'react';
import {usePathname} from './navigation';
type Packet='audio'|'video';
const key='erpi-device-channel';
export function DeviceArchive({source,unlocked}:{source:'phone'|'studio';unlocked:boolean}){
 const path=usePathname();const allowed=['/applications','/applications/companion','/applications/studio','/applications/ios'].includes(path);
 const [open,Open]=useState(false),[packets,Packets]=useState<Packet[]>([]),[sending,Sending]=useState<Packet|null>(null),[playing,Playing]=useState<Packet|null>(null),[found,Found]=useState(false);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const playback=useRef<ReturnType<typeof setTimeout>|null>(null);const sound=useRef<AudioContext|null>(null);
 useEffect(()=>{const read=()=>{try{const value=JSON.parse(sessionStorage.getItem(key)||'[]');Packets(Array.isArray(value)?value.filter((v:unknown)=>v==='audio'||v==='video'):[])}catch{Packets([])}};read();window.addEventListener('erpi:packet',read);return()=>window.removeEventListener('erpi:packet',read)},[]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(playback.current)clearTimeout(playback.current);void sound.current?.close()},[]);
 useEffect(()=>{Open(false);Playing(null);Sending(null);if(timer.current)clearTimeout(timer.current);if(playback.current)clearTimeout(playback.current);void sound.current?.close();sound.current=null},[path]);
 function send(type:Packet){if(sending)return;Sending(type);timer.current=setTimeout(()=>{let next=packets;try{const current=JSON.parse(sessionStorage.getItem(key)||'[]');next=Array.isArray(current)?current.filter((v:unknown)=>v==='audio'||v==='video'):[]}catch{}next=Array.from(new Set([...next,type]));try{sessionStorage.setItem(key,JSON.stringify(next))}catch{}Packets(next);Sending(null);window.dispatchEvent(new Event('erpi:packet'))},1800)}
 async function play(type:Packet){if(playback.current)clearTimeout(playback.current);if(sound.current){await sound.current.close();sound.current=null}if(playing===type){Playing(null);return}Playing(type);if(type==='audio'){try{const ctx=new AudioContext();sound.current=ctx;await ctx.resume();[0,.2,.4,1,1.5,2,2.7,2.9,3.1].forEach((offset,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=430;gain.gain.setValueAtTime(0,ctx.currentTime+offset);gain.gain.linearRampToValueAtTime(.035,ctx.currentTime+offset+.015);gain.gain.linearRampToValueAtTime(0,ctx.currentTime+offset+(i>=3&&i<=5?.32:.12));osc.connect(gain).connect(ctx.destination);osc.start(ctx.currentTime+offset);osc.stop(ctx.currentTime+offset+.4)})}catch{Playing(null);return}}playback.current=setTimeout(()=>{Playing(null);Found(true);void sound.current?.close();sound.current=null},type==='audio'?3800:6500)}
 if(!allowed||(!unlocked&&packets.length===0))return null;
 return <div className="device-archive"><button className="archive-channel" onClick={()=>Open(!open)} aria-expanded={open}>{source==='phone'?'014 / canal secondaire':`${packets.length} élément${packets.length>1?'s':''} reçu${packets.length>1?'s':''}`}</button>{open&&<div className="archive-drawer"><div className="archive-heading"><span>LOCAL / 03:14</span><button aria-label="Fermer le canal" onClick={()=>Open(false)}>×</button></div>{source==='phone'?<><p>Deux fichiers ne portent aucun marqueur.</p>{(['audio','video'] as Packet[]).map(type=><button className="packet-action" key={type} disabled={!!sending||packets.includes(type)} onClick={()=>send(type)}>{packets.includes(type)?'Transmis':sending===type?'Transmission…':'Transférer vers Studio'}<small>{type==='audio'?'014_SILENCE.wav':'014_PALIER.mov'}</small></button>)}{sending&&<div className="packet-progress" role="status" aria-label="Transfert local en cours"><i/></div>}<p className="channel-note">{packets.length?'Ouvrez les éléments reçus dans l’écran Studio.':'Liaison locale disponible.'}</p></>:<><p>Session 014 / éléments sans auteur</p>{packets.map(type=><button className="packet-action" key={type} onClick={()=>void play(type)}>{playing===type?'Arrêter':type==='audio'?'Écouter le son':'Lire la séquence'}<small>{type==='audio'?'014_SILENCE.wav':'014_PALIER.mov'}</small></button>)}{playing==='video'&&<div className="archive-film"><img src="/darkroom.png" alt="Séquence fictive : une chambre noire vide"/><span>CAM 02 · 03:14</span><b>LA PORTE ÉTAIT DÉJÀ OUVERTE.</b></div>}{playing==='audio'&&<div className="archive-signal" role="status">••• — — — •••</div>}{found&&<p className="channel-answer">Lisez le silence entre les trois coups.<br/>Archive 014 / fragment retrouvé.</p>}</>}<small className="channel-note">Séquence narrative · aucun fichier personnel transmis.</small></div>}</div>
}
