export type Lesson={title:string;goal:string;steps:string[];diagram:string[];example:string;exercise:string;answer:string;question:string;options:string[];correct:number;explanation:string};
export const curricula:Record<string,{intro:string;kit:string;project:string;lessons:Lesson[]}>= {
'premiere-enquete':{intro:'Un parcours autonome pour passer d’un récit intriguant à un dossier lisible et vérifiable. Aucun équipement spécialisé n’est nécessaire pour les exercices.',kit:'Un carnet, une montre, un téléphone et une pièce familière dont vous avez l’autorisation d’usage. Les exercices se font à domicile, de jour.',project:'Produisez un mini-dossier de deux pages : question, contexte, observations horodatées, comparaison et conclusion limitée aux éléments recueillis.',lessons:[
{title:'Poser une question vérifiable',goal:'Séparer une observation, un témoignage et une interprétation.',steps:[
'Une enquête commence par une question assez précise pour guider une vérification. « Ce lieu est-il hanté ? » ne désigne pas un test. « Dans quelles conditions entend-on les trois coups décrits près de la fenêtre ? » permet de décider où observer, quand et avec quels repères.',
'Créez trois colonnes dans votre carnet. Fait observé : ce que vous avez personnellement constaté. Témoignage : ce qu’une autre personne rapporte. Hypothèse : une explication que vous allez examiner. N’effacez pas un témoignage lorsque vous trouvez une explication ; ajoutez le résultat à côté pour conserver le cheminement.',
'Commencez l’entretien par « Racontez ce qui s’est passé ». Demandez ensuite l’heure approximative, la durée, la position des personnes et les changements remarqués. Évitez de suggérer une silhouette, une voix ou une cause avant que la personne ait décrit ses souvenirs. Consignez les incertitudes : « vers 22 h » n’est pas « 22 h 00 ».'
],diagram:['Récit','Question précise','Observation prévue'],example:'« Une présence a frappé au mur » devient : « Le témoin rapporte trois coups, vers 22 h, côté fenêtre ; la source du bruit n’a pas été vue. »',exercise:'Réécrivez « Un fantôme a allumé la lampe quand je suis entré » en distinguant observation rapportée et interprétation. Formulez deux questions neutres.',answer:'Observation rapportée : la lampe s’est allumée à l’entrée du témoin. Interprétation : l’attribution à un fantôme. Questions possibles : quel type d’interrupteur équipe la lampe ? Qui était présent et où ? Le déclenchement seul ne renseigne pas sur son origine.',question:'Quelle formulation peut orienter un test ?',options:['Le lieu dégage une énergie étrange.','La porte bouge-t-elle quand la fenêtre est ouverte ?','Une présence cherche à communiquer.'],correct:1,explanation:'Une condition observable, la fenêtre ouverte, est reliée à un événement défini, le mouvement de la porte.'},
{title:'Préparer le terrain',goal:'Définir un périmètre, les rôles et une situation de référence.',steps:[
'Choisissez pour cet exercice un lieu familier et autorisé. Repérez les passages, les sorties et les zones où il est possible de rester sans gêner. Une investigation n’exige pas le noir : commencez de jour et gardez les déplacements éclairés. Un endroit dont la stabilité ou l’accès est incertain ne convient pas à cet apprentissage.',
'Avant de chercher un signal inhabituel, décrivez ce qui est habituel. Notez les fenêtres ouvertes, la ventilation audible, les sources lumineuses et les personnes présentes. Dessinez un plan simple avec votre position et celle du téléphone. Ce relevé de départ constitue la référence de comparaison.',
'À deux, attribuez un rôle d’observation et un rôle de prise de notes ; inversez-les à mi-parcours. Annoncez les déplacements et les manipulations. Vérifiez l’heure affichée par vos appareils et notez tout décalage. Décidez avant le début de la durée de l’exercice et des raisons d’arrêter : fatigue, gêne, perte de visibilité ou demande du propriétaire.'
],diagram:['Autorisation','Repérage','Référence','Consignes'],example:'Dans un salon, un observateur reste assis à deux mètres de la porte. Le téléphone est posé sur un support fixe. La fenêtre est d’abord fermée et la ventilation reste dans son état habituel.',exercise:'Préparez une fiche de séance de dix minutes avec un plan, deux rôles, trois conditions de départ et deux critères d’arrêt.',answer:'La fiche doit permettre à quelqu’un d’autre de placer le matériel au même endroit. Exemples de conditions : porte entrouverte, fenêtre fermée, deux personnes immobiles. Exemples d’arrêt : demande d’un occupant, passage devenu encombré.',question:'À quoi sert la situation de référence ?',options:['À garantir qu’aucun phénomène ne se produira.','À obtenir une ambiance impressionnante.','À comparer un changement à un état documenté.'],correct:2,explanation:'Une référence documentée permet de savoir quelles conditions ont réellement changé.'},
{title:'Consigner sans perdre le contexte',goal:'Créer une trace exploitable et préserver les originaux.',steps:[
'Utilisez une ligne par événement : heure, position, observation, action des personnes, fichier associé. Écrivez « claquement bref côté couloir » avant de chercher un nom à ce bruit. Notez aussi les moments sans événement : ils montrent ce qui a été observé pendant la séance, au-delà des seuls passages surprenants.',
'Pour chaque photo ou séquence, conservez le fichier original et ses voisins temporels. Une courte extraction est pratique pour discuter, mais elle doit renvoyer à la source complète et à son horodatage. N’envoyez pas uniquement une capture d’écran recadrée : elle élimine des informations utiles.',
'Adoptez un classement simple : un dossier de séance, un sous-dossier originaux que vous ne modifiez pas, un sous-dossier copies et un journal. Nommez les fichiers sans renseignements personnels, par exemple SEANCE-01_AUDIO-A. Si vous modifiez une copie, inscrivez l’opération dans le journal. La facilité à retrouver les pièces compte davantage qu’une nomenclature compliquée.'
],diagram:['Original','Copie de travail','Journal','Extrait repéré'],example:'22:04:12 — claquement bref — observateur côté table — second participant ouvre son carnet — fichier AUDIO-A, repère 02:12.',exercise:'Créez trois lignes de journal fictives, dont une sans événement et une avec une manipulation. Associez un nom de fichier et un repère à chaque élément enregistré.',answer:'Une bonne ligne situe l’événement et ses conditions sans transformer une coïncidence en cause. La mention du carnet reste une piste à vérifier ; elle ne suffit pas à attribuer le claquement.',question:'Quelle pièce faut-il préserver ?',options:['Le fichier original avec son contexte.','Seulement l’extrait le plus étrange.','Uniquement une version fortement amplifiée.'],correct:0,explanation:'L’original permet de réexaminer les séquences et de comparer les traitements ultérieurs.'},
{title:'Comparer des explications',goal:'Tester une hypothèse sans changer plusieurs conditions à la fois.',steps:[
'Écrivez au moins deux explications possibles avant le test. Pour un mouvement de porte : courant d’air, passage d’une personne, irrégularité du maintien. Associez à chacune un résultat attendu. Si une hypothèse ne prévoit aucune différence observable, votre expérience ne permettra pas de la départager.',
'Changez une condition à la fois. Faites une observation fenêtre fermée, puis ouverte, avec la porte et votre position identiques. Répétez plusieurs fois et notez également les essais sans mouvement. Évitez de modifier une installation électrique ou un équipement dangereux pour créer un effet : limitez-vous à des manipulations ordinaires autorisées.',
'La reproduction d’un effet montre qu’une cause peut le produire dans les conditions testées. Elle ne prouve pas automatiquement que cette cause était présente lors du témoignage initial. Comparez précisément les conditions historiques et actuelles, puis indiquez celles qui vous échappent.'
],diagram:['Hypothèse','Prédiction','Comparaison','Limites'],example:'La porte bouge dans trois essais sur trois avec la fenêtre ouverte et dans zéro essai sur trois fenêtre fermée. Cela soutient l’explication par circulation d’air pour cette séance ; l’état de la fenêtre lors du récit initial reste inconnu.',exercise:'Définissez un petit test de bruit dans votre pièce : deux conditions, trois essais par condition et un tableau où noter tous les résultats.',answer:'Exemple : bruit de chaise sur le même sol, avec puis sans déplacement de la chaise. Conservez position et enregistreur. Notez les six essais, y compris les absences de bruit. Une ressemblance seule ne démontre pas l’origine du bruit initial.',question:'Le bruit a été reproduit. Que peut-on conclure ?',options:['Tout le témoignage est faux.','Une cause possible a été identifiée dans les conditions du test.','Tous les bruits du lieu ont cette origine.'],correct:1,explanation:'La conclusion porte sur ce qui a été testé. Elle ne doit pas dépasser les données recueillies.'},
{title:'Rédiger et restituer le dossier',goal:'Présenter un résultat utile, même quand il reste indéterminé.',steps:[
'Votre rapport final suit six rubriques : question initiale, contexte, méthode, observations, hypothèses et conclusion. Numérotez les pièces et reliez chaque affirmation importante à une ligne du journal ou à un fichier. Une personne absente doit pouvoir comprendre ce qui a été fait sans demander les souvenirs de l’équipe.',
'Distinguez une explication testée, une explication plausible non testée et une origine indéterminée. Mentionnez les limites : pas d’accès à une pièce, horaire approximatif, séquence manquante ou séance trop courte. « Nous ne savons pas » est un résultat précis lorsque vous expliquez ce qui manque pour progresser.',
'Présentez les résultats au témoin avec une formulation respectueuse. Une explication ordinaire ne rend pas son expérience insignifiante. Pour une version publique, retirez les informations qui identifient inutilement les personnes et le lieu. Relisez les titres et légendes : ils doivent refléter la conclusion, pas promettre plus que le dossier.'
],diagram:['Question','Pièces','Analyse','Conclusion limitée'],example:'Conclusion : un bruit comparable a été reproduit par la chaise. Faute d’enregistrement original du témoignage, son origine reste indéterminée. Prochaine étape possible : documenter un nouvel événement dans des conditions connues.',exercise:'Réalisez le mini-dossier final de deux pages. Ajoutez une conclusion de quatre phrases : résultat, preuve, limite, prochaine étape.',answer:'Auto-évaluation : les six rubriques sont présentes ; les faits et récits sont distingués ; chaque pièce a une référence ; au moins une alternative est examinée ; la conclusion mentionne une limite ; les données personnelles inutiles sont absentes.',question:'Quelle est la meilleure conclusion ?',options:['Aucun événement ne s’est produit, donc rien n’a jamais eu lieu.','Le mystère est forcément paranormal.','Aucun événement comparable n’a été observé pendant les dix minutes de séance.'],correct:2,explanation:'La troisième proposition définit exactement le périmètre de l’observation, sans généralisation.'}
]},
'analyse-audio':{intro:'Un laboratoire d’écoute accessible pour enregistrer, comparer et présenter un son sans transformer une impression en preuve.',kit:'Un ordinateur avec un éditeur audio, un téléphone ou un enregistreur, un casque à volume confortable et un carnet. Utilisez vos propres sons non sensibles.',project:'Constituez un dossier audio avec original, journal de traitement, relevé d’écoute indépendante et conclusion argumentée.',lessons:[
{title:'Comprendre ce que le microphone capte',goal:'Distinguer un signal enregistré de son interprétation.',steps:[
'Un microphone transforme les variations de pression sonore en un signal électrique ; l’enregistrement numérique en conserve des échantillons. La piste représente ce qui a atteint ce capteur à sa position. Elle ne fournit pas, à elle seule, l’identité de la source ni son intention.',
'Le placement change fortement le résultat. Un téléphone posé sur une table peut capter des vibrations transmises par le support. Un frottement sur le boîtier peut dominer un bruit éloigné. Commencez par identifier les sons ordinaires de votre pièce et les manipulations que vous risquez de faire pendant la prise.',
'Pour ce cours, ne partez pas d’une vidéo déjà montée. Fabriquez un échantillon connu : annoncez le début de séance, restez silencieux quelques secondes, froissez une feuille à distance, annoncez la fin. Notez position, appareil et durée. Vous disposez ainsi d’une référence dont la source est connue.'
],diagram:['Source sonore','Pièce et support','Microphone','Fichier'],example:'Le même froissement est enregistré avec le téléphone posé sur la table puis sur un support distinct. L’écart entre les prises peut venir du placement, pas d’un changement de source.',exercise:'Enregistrez trente secondes comprenant du silence ambiant, un froissement et un tapotement annoncé. Notez les repères sans traiter la piste.',answer:'Votre journal doit permettre d’associer les deux sons à leurs moments. L’absence de son volontaire reste une ambiance enregistrée, pas nécessairement un signal nul.',question:'Une forme d’onde permet-elle d’identifier une personne ?',options:['Oui, dès qu’un pic apparaît.','Non, elle montre des variations du signal, pas une identité.','Oui, si on la colore.'],correct:1,explanation:'La visualisation sert à repérer et comparer des événements ; l’identité exige d’autres éléments.'},
{title:'Obtenir une prise exploitable',goal:'Contrôler le niveau et documenter la chaîne de capture.',steps:[
'Avant la vraie prise, faites un essai avec le son le plus fort attendu. Surveillez l’indicateur de niveau de votre logiciel ou appareil. Un niveau trop élevé peut saturer ; le baisser après l’enregistrement ne restitue pas l’information perdue. Choisissez une marge plutôt que de chercher constamment le niveau maximum.',
'Gardez une position stable, évitez de toucher l’appareil et annoncez les manipulations inévitables. Notez les réglages accessibles : format, fréquence d’échantillonnage, canaux et traitement automatique éventuel. Si votre téléphone impose certains réglages, indiquez simplement qu’ils sont inconnus.',
'Conservez le fichier natif reçu de l’appareil. Pour travailler, faites une copie ; exporter un fichier déjà compressé en WAV n’invente pas les détails supprimés auparavant. Vérifiez enfin que le début et la fin sont présents et que le son est lisible avant de quitter votre séance.'
],diagram:['Essai de niveau','Prise stable','Contrôle','Copie'],example:'Une prise présente un claquement déformé au moment où le microphone est touché. Ce passage sera signalé comme perturbé, même si une amplification ultérieure le rend plus audible.',exercise:'Réalisez deux prises du même son à distance fixe : une avec un réglage prudent, une après changement modéré du niveau si disponible. Comparez sans rechercher volontairement une saturation.',answer:'Notez ce qui change : volume perçu, bruit de fond, déformation éventuelle. Ne déduisez pas une différence de source quand seul le réglage a changé.',question:'Convertir un MP3 en WAV…',options:['Restaure tous les détails perdus.','Prouve que la prise est originale.','Ne restaure pas les informations déjà perdues.'],correct:2,explanation:'Le changement de conteneur ou de format ne reconstitue pas les données absentes.'},
{title:'Écouter sans suggérer une phrase',goal:'Recueillir plusieurs écoutes indépendantes.',steps:[
'Avant de partager votre interprétation, faites écouter l’extrait sans titre suggestif, sous-titres ou phrase attendue. Demandez une description libre : bruit, voix possible, rythme, nombre d’événements. Acceptez « je ne sais pas ». Un choix forcé peut donner un accord apparent qui ne reflète pas l’écoute.',
'Conservez les réponses séparément avant discussion. Comparez ensuite les transcriptions et le degré de certitude. Une convergence mérite d’être examinée mais ne suffit pas à établir une origine ; une divergence indique que la lecture est ambiguë dans ces conditions.',
'Limitez les répétitions et prenez des pauses. Revenez au passage avec quelques secondes avant et après. Notez le matériel d’écoute et gardez un volume confortable. N’évaluez pas seulement le fragment le plus frappant : une conversation hors champ ou une manipulation voisine peut fournir du contexte.'
],diagram:['Extrait neutre','Réponses séparées','Comparaison','Contexte'],example:'Trois personnes décrivent respectivement un souffle, deux syllabes et un froissement. Le rapport conserve cette diversité au lieu d’annoncer une phrase entendue par tous.',exercise:'Faites écouter votre froissement à deux personnes sans nommer sa source. Recueillez leurs descriptions, puis révélez la source et comparez les commentaires.',answer:'Cherchez surtout les changements de description après révélation. L’exercice illustre l’intérêt de recueillir une première réponse non orientée ; deux personnes ne constituent pas une étude scientifique.',question:'Que transmettre lors de la première écoute ?',options:['Un extrait neutre et une demande de description libre.','La phrase que vous espérez entendre.','Un sous-titre affirmatif.'],correct:0,explanation:'Une consigne neutre évite de fournir directement l’interprétation à retrouver.'},
{title:'Traiter avec parcimonie',goal:'Comparer un traitement à l’original et documenter ses limites.',steps:[
'Commencez sur une copie et enregistrez une version avant chaque opération. L’amplification change le niveau, pas l’origine. Un filtre modifie le contenu fréquentiel ; une réduction de bruit peut également retirer des éléments utiles ou produire des artefacts. Un résultat plus net n’est donc pas automatiquement plus fidèle.',
'Dans Audacity, la réduction de bruit s’appuie sur un échantillon du bruit à atténuer. Consultez le manuel lié en fin de cours et vérifiez que le passage choisi ne contient pas le son que vous souhaitez étudier. Essayez un réglage modéré et écoutez l’original, la version traitée et, si disponible, le résidu retiré.',
'Inscrivez le nom de l’effet, les valeurs, la sélection concernée et l’ordre des opérations. Comparez à volume perçu proche pour éviter de préférer une version simplement plus forte. Si un effet fait apparaître une phrase absente ou ambiguë dans l’original, présentez-la comme dépendante du traitement, pas comme une révélation.'
],diagram:['Copie','Effet documenté','Comparaison A/B','Conserver ou annuler'],example:'Après une réduction agressive, de petites tonalités apparaissent dans le souffle. L’équipe revient à l’original et écarte ce traitement pour l’interprétation du passage.',exercise:'Sur votre propre piste, appliquez une seule modification légère. Notez les paramètres et rédigez deux colonnes : ce qui aide l’écoute, ce qui devient moins fiable.',answer:'Le journal doit identifier exactement la version. Si vous ne pouvez pas décrire un bénéfice clair sans perte gênante, annulez l’effet. Conserver l’original sans traitement est une décision valable.',question:'Une phrase apparaît seulement après un traitement fort. Que faire ?',options:['La publier comme une preuve certaine.','Comparer à l’original et signaler la dépendance au traitement.','Supprimer l’original.'],correct:1,explanation:'Le traitement fait partie des conditions de lecture et doit rester visible dans l’analyse.'},
{title:'Présenter une analyse reproductible',goal:'Livrer les pièces et une conclusion proportionnée.',steps:[
'Rassemblez le fichier source, l’extrait non traité, une éventuelle copie traitée, le journal et les réponses d’écoute. Donnez à chaque élément une référence simple. Votre lecteur doit retrouver le passage dans la source et savoir quelle version il écoute sans deviner.',
'Rédigez le résultat en décrivant d’abord le son : durée, caractère intermittent ou continu, contexte de capture. Présentez les hypothèses ordinaires examinées, ce qui les soutient et ce qui manque. Le terme EVP désigne une interprétation de certains enregistrements ; il ne constitue pas une identification technique de leur origine.',
'Votre conclusion distingue audibilité, intelligibilité et attribution. Un son peut être audible sans former une phrase ; une phrase peut être compréhensible sans source identifiée. Archivez les fichiers pour permettre une autre lecture et évitez de publier des conversations privées sans accord des personnes concernées.'
],diagram:['Source','Versions','Écoutes','Conclusion'],example:'Un son bref est audible au repère 00:14. Les descriptions des auditeurs divergent. Un frottement est plausible mais non confirmé par l’image. L’origine reste indéterminée.',exercise:'Finalisez votre dossier audio : cinq pièces référencées, un tableau des écoutes et une conclusion de cent mots maximum. Ajoutez une limite explicite.',answer:'Vérifiez : source conservée, repères exacts, traitements listés, réponses indépendantes conservées et conclusion sans attribution non étayée. Votre propre source connue permet de comparer ensuite votre rédaction au déroulement réel.',question:'Un son audible mais non identifié est…',options:['Nécessairement une voix.','Nécessairement paranormal.','Un son dont l’origine n’est pas établie avec les éléments disponibles.'],correct:2,explanation:'Une absence d’identification ne constitue pas une preuve positive d’une autre origine.'}
]}};
export const articles=[
{id:'avant-la-premiere-nuit',title:'Préparer une première séance d’observation',category:'Terrain',read:'5 min',intro:'Le travail le plus utile commence souvent bien avant d’éteindre la lumière. Voici comment préparer une observation qui pourra être relue.',diagram:['Écouter','Préparer','Observer','Documenter'],sections:[
['Définir ce que l’on cherche','Un récit étrange attire immédiatement les hypothèses. Pourtant, la première décision utile consiste à ralentir : quel événement précis souhaite-t-on comprendre ? Un bruit, un mouvement ou une lumière n’appellent pas les mêmes observations. Poser une question limitée évite de transformer chaque détail du lieu en indice. Une séance de dix minutes autour d’une porte peut produire un dossier plus exploitable qu’une longue nuit sans journal.'],
['Faire connaissance avec le lieu','Commencez dans les conditions habituelles du lieu. Regardez où passent les personnes, d’où vient la lumière, quels objets peuvent bouger. Consignez ces éléments avant la séance, car les souvenirs se recomposent facilement après un moment marquant. Un croquis très simple suffit : position de l’observateur, du téléphone et de l’élément surveillé. L’accès doit être autorisé et les déplacements rester sûrs.'],
['Préparer les moments ordinaires','Le journal ne sert pas seulement à noter les surprises. Une personne qui se lève, un carnet que l’on ouvre ou une fenêtre que l’on ferme sont des informations qui pourront expliquer un enregistrement. Annoncez ces actions et notez l’heure. Gardez également une trace des périodes sans événement. Elles donnent une durée réelle à la séance et empêchent le montage de devenir le seul récit disponible.'],
['Revenir avec une question mieux posée','La réussite d’une première observation ne se mesure pas au nombre de phénomènes rapportés. Elle tient à la possibilité de comprendre les conditions, de retrouver les pièces et de proposer un test suivant. Une séance sans résultat spectaculaire peut avoir éliminé une confusion ou montré qu’un appareil était mal placé. C’est déjà une progression : le dossier gagne en précision, même si le mystère n’a pas de conclusion.']],takeaway:'Une bonne enquête laisse une trace que quelqu’un d’autre peut comprendre.',course:'premiere-enquete'},
{id:'son-etrange',title:'Examiner un enregistrement ambigu',category:'Laboratoire audio',read:'5 min',intro:'Entre ce que capte le microphone et ce que nous croyons entendre, il y a plusieurs étapes à garder visibles.',diagram:['Son capté','Écoute neutre','Comparaison','Interprétation'],sections:[
['L’original est le point de départ','Un extrait circule vite. Il arrive souvent accompagné d’une phrase proposée, d’un titre ou d’un sous-titre. Pour l’examiner, revenez au fichier le plus proche possible de la capture et écoutez ce qui précède et suit. La question initiale est descriptive : combien de sons, quelle durée, quelle variation ? Nommer immédiatement une voix enferme déjà la lecture.'],
['Recueillir les écoutes avant la discussion','Demandez à plusieurs personnes de décrire le passage sans leur donner votre phrase. Conservez leurs réponses avant de les réunir. Certains entendront un rythme, d’autres une syllabe, d’autres rien d’identifiable. Ces différences font partie du résultat. Un accord après discussion ne se confond pas avec plusieurs descriptions indépendantes. Il est utile de distinguer les deux dans le compte rendu.'],
['Rendre le traitement visible','Une copie amplifiée ou filtrée peut aider à localiser un détail, mais chaque opération change les conditions d’écoute. Le manuel d’Audacity rappelle notamment que la réduction de bruit peut introduire des artefacts et retirer des sons utiles. Conservez les paramètres et comparez à l’original. Le son qui paraît plus impressionnant après traitement n’est pas nécessairement plus informatif.'],
['Conclure à la bonne échelle','Audible, intelligible et identifié sont trois niveaux différents. Entendre clairement quelque chose ne signifie pas reconnaître des mots ; reconnaître des mots ne renseigne pas encore sur la source. Une conclusion utile nomme le niveau atteint, les pistes examinées et ce qui manque. Un son indéterminé reste un son indéterminé, même lorsque son écoute est troublante.']],takeaway:'Avant « qu’est-ce que cela veut dire ? », demander « qu’entend-on réellement ? ».',course:'analyse-audio'},
{id:'carnet-enquete',title:'Tenir un carnet d’enquête',category:'Méthodologie',read:'4 min',intro:'Une heure, une position et une action notées au bon moment peuvent changer toute la lecture d’un dossier.',diagram:['Heure','Observation','Contexte','Pièce'],sections:[
['Écrire pour une personne absente','Imaginez que vous transmettrez votre carnet à quelqu’un qui n’était pas sur place. « Gros bruit bizarre » ne lui permet pas de chercher. « 21 h 17, claquement bref côté couloir, deux personnes assises, porte entrouverte » lui donne déjà des repères. L’objectif n’est pas d’écrire beaucoup, mais de conserver ce qui ne pourra pas être reconstruit avec certitude après la séance.'],
['Garder les catégories distinctes','Dans une ligne, séparez ce que vous constatez, ce qu’un témoin raconte et ce que vous supposez. « Le témoin rapporte un pas » conserve la provenance de l’information. « Un pas a été entendu » la rend plus ambiguë. Vous pouvez proposer une explication dans une autre colonne sans la fondre dans la description. Cette discipline rend les désaccords plus faciles à discuter.'],
['Relier le papier aux fichiers','Une référence courte suffit si elle est constante. Donnez un nom à chaque prise, puis inscrivez le repère temporel à côté de l’événement. Vérifiez les décalages d’horloge entre vos appareils. Si vous ignorez l’heure exacte, indiquez une approximation au lieu d’inventer une précision. Les extraits partagés doivent conserver le nom de la source et leur position dans cette source.'],
['Corriger sans effacer le chemin','Une note peut être complétée après vérification. Gardez l’observation initiale et ajoutez la correction datée : « bruit reproduit lors du déplacement de la chaise ». Le journal devient alors l’histoire de l’analyse, pas seulement une liste d’événements sélectionnés. Une page sobre et lisible est plus utile qu’une mise en scène d’archives dont les références ne mènent à aucune pièce.']],takeaway:'Le carnet donne aux images et aux sons ce qu’ils ne conservent pas toujours : leur contexte.',course:'premiere-enquete'},
{id:'indetermine',title:'Quand une enquête reste sans explication',category:'Esprit critique',read:'4 min',intro:'On peut prendre un témoignage au sérieux tout en reconnaissant que les éléments disponibles ne suffisent pas à expliquer son origine.',diagram:['Question','Éléments disponibles','Limites','Statut'],sections:[
['Ce que le dossier permet réellement','Une investigation se déroule dans un lieu, pendant une durée et avec un matériel donné. Elle n’observe pas tous les moments du passé. Lorsque le phénomène décrit ne se reproduit pas, cela renseigne sur la séance menée. Cela ne suffit ni à invalider chaque souvenir du témoin ni à confirmer une cause extraordinaire. La conclusion doit rester à cette échelle.'],
['Distinguer absence et impossibilité','Une image manquante, une horloge non synchronisée ou une pièce inaccessible réduisent ce que l’on peut vérifier. Ces limites n’indiquent pas que toute vérification serait impossible. Elles précisent ce qui manque aujourd’hui. Les mentionner rend le dossier plus solide, parce qu’un autre lecteur peut proposer une observation complémentaire plutôt que deviner les lacunes.'],
['Ne pas faire du mystère une preuve','Lorsque plusieurs explications ordinaires restent compatibles avec les faits, il n’est pas nécessaire d’en choisir une artificiellement. À l’inverse, ne pas en trouver ne démontre pas une autre origine. Une hypothèse a besoin d’éléments qui la soutiennent, pas seulement de l’échec des hypothèses concurrentes. Le mot « inexpliqué » décrit un état des connaissances du dossier.'],
['Préparer une suite proportionnée','Une bonne clôture peut proposer une action simple : noter les horaires d’un nouveau bruit, conserver une séquence complète ou comparer deux conditions d’ouverture d’une porte. Elle peut aussi constater qu’il n’existe pas de prochaine étape utile. Respecter cette limite évite d’entretenir artificiellement une enquête. Le témoin reçoit un résultat clair, sans promesse d’une certitude future.']],takeaway:'La précision sur ce que l’on ignore fait partie de la méthode.',course:'premiere-enquete'},
{id:'publier-un-dossier',title:'Rédiger un dossier consultable',category:'Archives',read:'5 min',intro:'Publier une enquête, c’est permettre au lecteur de suivre le raisonnement, au-delà du seul moment spectaculaire.',diagram:['Journal','Pièces référencées','Analyse','Publication'],sections:[
['Faire de la place au contexte','Un titre attire l’attention, mais il ne doit pas remplacer le contenu. Ouvrez le dossier par la question initiale et les conditions de la séance. Indiquez ce qui provient du récit du témoin et ce qui a été observé par l’équipe. Si les exemples sont fictifs ou reconstitués, dites-le à proximité : la mise en forme ne doit pas créer l’apparence d’un document authentique.'],
['Rendre les pièces navigables','Numérotez les photographies, les prises audio et les séquences. Associez chaque extrait à sa source et à son repère. Une légende utile dit ce que l’image montre, comment elle a été obtenue et si elle a été modifiée. Une légende qui impose déjà une origine retire au lecteur une part de sa possibilité d’examen.'],
['Présenter les alternatives','Le rapport gagne en intérêt lorsqu’il explique comment une piste a été étudiée. Qu’attendait-on du test ? Qu’a-t-on observé ? Quelles conditions ont changé ? Les résultats ordinaires ne sont pas des passages à cacher : ils montrent le travail accompli et permettent de comprendre pourquoi une autre question reste ouverte. Un tableau d’hypothèses peut être plus éclairant qu’une succession de conclusions affirmatives.'],
['Terminer avec une version datée','Ajoutez la date de mise à jour et distinguez le résultat actuel des étapes précédentes. Un dossier peut évoluer avec une nouvelle pièce. Une version publique doit aussi limiter les détails qui identifient inutilement un témoin ou une habitation. La transparence sur la méthode n’exige pas de tout exposer sur les personnes : ces deux objectifs peuvent être tenus ensemble.']],takeaway:'Un dossier convaincant permet de suivre une enquête, pas seulement d’y croire.',course:'premiere-enquete'}
];
