'use client';
import {useEffect,useRef,useState} from 'react';
import {LampCeiling,Ghost,ArrowRight,CalendarDays} from 'lucide-react';
import Link,{usePathname} from './navigation';
export function Experience(){
 const path=usePathname();const[open,Open]=useState(false);const[lit,Lit]=useState(false);const[drag,Drag]=useState(0);const start=useRef(0);const cursor=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{try{if(!sessionStorage.getItem('erpi-entered')&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&localStorage.getItem('erpi-motion')!=='off')Open(true)}catch{}return()=>{if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>{const replay=()=>{Lit(false);Drag(0);Open(true)};window.addEventListener('erpi:intro',replay);return()=>window.removeEventListener('erpi:intro',replay)},[]);
 const enter=()=>{Lit(true);try{sessionStorage.setItem('erpi-entered','1')}catch{}timer.current=setTimeout(()=>Open(false),850)};
 useEffect(()=>{if(!open)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';const previous=document.activeElement as HTMLElement|null;const background=Array.from(document.querySelectorAll<HTMLElement>('.sitehead,.subnav,#main,.footwrap,.workbar'));background.forEach(el=>el.inert=true);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')enter();if(e.key==='Tab'){const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('.darkroom-entry button'));const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=prev;background.forEach(el=>el.inert=false);if(previous?.isConnected)previous.focus();else document.querySelector<HTMLAnchorElement>('.sitehead a')?.focus({preventScroll:true});window.removeEventListener('keydown',key)}},[open]);
 useEffect(()=>{const fine=matchMedia('(pointer: fine)');if(!fine.matches)return;const move=(e:PointerEvent)=>{if(!cursor.current)return;cursor.current.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`;cursor.current.dataset.active=String(!!(e.target as Element)?.closest('a,button,summary'));cursor.current.dataset.hidden=String(!!(e.target as Element)?.closest('input,textarea,select'));cursor.current.style.opacity='1'};const leave=()=>{if(cursor.current)cursor.current.style.opacity='0'};window.addEventListener('pointermove',move,{passive:true});document.addEventListener('pointerleave',leave);return()=>{window.removeEventListener('pointermove',move);document.removeEventListener('pointerleave',leave)}},[]);
 return <><div ref={cursor} className="investigator-cursor" aria-hidden="true"><span/></div><div key={path} className="page-shutter" aria-hidden="true"/>{open&&<div className={'darkroom-entry '+(lit?'is-lit':'')} role="dialog" aria-modal="true" aria-labelledby="entry-title"><div className="entry-lamp"><LampCeiling size={92} strokeWidth={.8}/><button autoFocus className="lamp-cord" aria-label="Tirer la corde pour allumer la lampe" style={{'--pull':`${drag}px`} as React.CSSProperties} onPointerDown={e=>{start.current=e.clientY;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))Drag(Math.max(0,Math.min(100,e.clientY-start.current)))}} onPointerUp={()=>{Drag(0);enter()}} onPointerCancel={()=>Drag(0)} onClick={()=>{if(!lit)enter()}}><span/><i/></button></div><div className="entry-copy"><p className="eyebrow">ERPI PARANORMAL / CHAMBRE NOIRE</p><h2 id="entry-title">Toute enquête commence<br/>par un peu de lumière.</h2><p>Tirez sur la corde. L’inexpliqué vous attend.</p><button className="textlink" onClick={enter}>Entrer directement →</button></div></div>}</>
}
export function Ghost404(){return <section className="ghost-page"><p className="eyebrow">ARCHIVES ERPI / PIÈCE MANQUANTE</p><div className="ghost-code"><span>4</span><Ghost size={130} strokeWidth={1}/><span>4</span></div><h1>Cette page nous a<br/>fait un ghosting.</h1><p>On lui a demandé un signe.<br/>Elle nous a répondu « page introuvable ».</p><div className="actions"><Link className="button primary" href="/dossiers">Reprendre l’enquête <ArrowRight size={17}/></Link><Link className="button" href="/">Retour en lieu sûr</Link><Link className="textlink" href="/recherche">Rechercher une piste</Link></div><p className="small">Hypothèse retenue : adresse erronée ou page déplacée.<br/>Le fantôme bénéficie de la présomption d’innocence.</p></section>}
export function AppointmentCTA(){return <section className="appointment-callout"><div><p className="eyebrow">UN PREMIER ÉCHANGE, SIMPLEMENT</p><h2>Parlons de vos observations.</h2><p>Choisissez un entretien téléphonique ou une visio pour préparer votre demande.</p></div><Link className="button primary" href="/rendez-vous"><CalendarDays size={19}/>Prendre rendez-vous</Link></section>}
export function SocialLinks(){return <section className="social-section"><div className="sectionhead"><div><p className="eyebrow">L’ENQUÊTE CONTINUE</p><h2>Sur le terrain. À l’écran.</h2></div><Link className="textlink" href="/medias">Les reportages →</Link></div><div className="social-grid"><a className="social-card" href="https://www.tiktok.com/@erpi_paranormal" target="_blank" rel="noreferrer"><img src="/brands/tiktok.svg" alt="" width="35" height="35"/><div><span className="eyebrow">TIKTOK</span><h3>@erpi_paranormal</h3><p>Retrouvez les formats courts du compte ERPI Paranormal.</p></div><span>↗</span></a><a className="social-card" href="https://www.youtube.com/results?search_query=ERPI+Paranormal" target="_blank" rel="noreferrer"><img src="/brands/youtube.svg" alt="" width="39" height="39"/><div><span className="eyebrow">YOUTUBE</span><h3>ERPI Paranormal</h3><p>Rechercher les vidéos ERPI sur YouTube.</p></div><span>↗</span></a></div><p className="small">TikTok : compte référencé sous ce nom. YouTube : recherche directe en attendant la confirmation de l’adresse de la chaîne.</p></section>}
