'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Ghost,ArrowRight,CalendarDays} from 'lucide-react';
import Link,{usePathname} from './navigation';
export function Experience(){
 const path=usePathname();const[open,Open]=useState(false);const[lit,Lit]=useState(false);const[drag,Drag]=useState(0);const start=useRef(0);const pulled=useRef(0);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const started=useRef(false);const audio=useRef<AudioContext|null>(null);
 const finish=useCallback(()=>{Open(false);Lit(false);document.documentElement.dataset.room='lit';},[]);
 const enter=useCallback((skip=false)=>{if(started.current)return;started.current=true;try{sessionStorage.setItem('erpi-entered','1')}catch{}const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.motion==='off';{try{const context=new AudioContext();audio.current=context;const buffer=context.createBuffer(1,Math.floor(context.sampleRate*.045),context.sampleRate);const samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*Math.exp(-i/(samples.length*.17));const source=context.createBufferSource();source.buffer=buffer;const gain=context.createGain();gain.gain.value=.16;source.connect(gain);gain.connect(context.destination);source.start();source.onended=()=>{void context.close();audio.current=null}}catch{}}if(skip||reduced){finish();return}Lit(true);document.documentElement.dataset.room='igniting';timer.current=setTimeout(finish,3100)},[finish]);
 useEffect(()=>{const root=document.documentElement;let show=false;try{show=location.pathname==='/'&&!sessionStorage.getItem('erpi-entered')&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&localStorage.getItem('erpi-motion')!=='off'}catch{}if(show){root.dataset.room='dark';Open(true)}else root.dataset.room='lit';return()=>{if(timer.current)clearTimeout(timer.current);void audio.current?.close();root.dataset.room='lit'}},[]);
 useEffect(()=>{const replay=()=>{if(timer.current)clearTimeout(timer.current);started.current=false;pulled.current=0;Lit(false);Drag(0);document.documentElement.dataset.room='dark';Open(true)};window.addEventListener('erpi:intro',replay);return()=>window.removeEventListener('erpi:intro',replay)},[]);
 useEffect(()=>{document.documentElement.dataset.scene=(path==='/'||path.startsWith('/dossiers')||path==='/carte'||path==='/videos'||path==='/404')?'story':'professional'},[path]);
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null;const stage=document.querySelector<HTMLElement>('.site-stage');const prevOverflow=document.body.style.overflow;document.body.style.overflow='hidden';if(stage)stage.inert=true;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(timer.current)clearTimeout(timer.current);finish();try{sessionStorage.setItem('erpi-entered','1')}catch{}}if(e.key==='Tab'){const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('.darkroom-entry button, .darkroom-entry [role=button]'));const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=prevOverflow;if(stage)stage.inert=false;if(previous?.isConnected&&previous!==document.body)previous.focus({preventScroll:true});else document.querySelector<HTMLElement>('.sitehead a')?.focus({preventScroll:true});window.removeEventListener('keydown',key)}},[open,finish]);
 return <><div key={path} className="page-shutter" aria-hidden="true"/>{open&&<div className={'darkroom-entry real-light '+(lit?'is-lit':'')} role="dialog" aria-modal="true" aria-labelledby="entry-title"><div className="blackout-curtain" aria-hidden="true"/><div className="light-spill" aria-hidden="true"/><div className="light-cone" aria-hidden="true"/><div className="darkroom-dust" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="entry-lamp"><div className="lamp-fixture" role="button" tabIndex={0} aria-label="Toucher la lampe pour allumer le site" onClick={()=>enter()} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();enter()}}}><div className="lamp-wire"/><div className="lamp-socket"/><div className="lamp-shade"><div className="lamp-rim"/></div><div className="lamp-bulb"><i/></div><div className="lamp-halo"/></div><button autoFocus className="lamp-cord" aria-label="Tirer la corde pour allumer le site" style={{'--pull':`${drag}px`} as React.CSSProperties} onPointerDown={e=>{start.current=e.clientY;pulled.current=0;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)){pulled.current=e.clientY-start.current;Drag(Math.max(0,Math.min(84,pulled.current)))}}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);const distance=pulled.current;Drag(0);if(distance>=24||Math.abs(distance)<8)enter()}} onPointerCancel={()=>{pulled.current=0;Drag(0)}} onClick={e=>{if(e.detail===0)enter()}}><span/><i/></button></div><div className="entry-copy"><p className="eyebrow">ERPI PARANORMAL</p><h2 id="entry-title">Faites la lumière.</h2></div></div>}</>
}
export function ArchiveLight(){const[active,Active]=useState(false);const ref=useRef<HTMLDivElement>(null);const position=useRef({x:50,y:50});useEffect(()=>{const jacket=ref.current?.closest<HTMLElement>('.dossier-jacket');if(!jacket)return;jacket.classList.toggle('lamp-examining',active);if(!active)return;const move=(e:PointerEvent)=>{const r=jacket.getBoundingClientRect();position.current={x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))};jacket.style.setProperty('--lamp-x',position.current.x+'%');jacket.style.setProperty('--lamp-y',position.current.y+'%')};jacket.addEventListener('pointermove',move);jacket.addEventListener('pointerdown',move);return()=>{jacket.removeEventListener('pointermove',move);jacket.removeEventListener('pointerdown',move);jacket.classList.remove('lamp-examining')}},[active]);return <div ref={ref} className="archive-light-control"><button className="button" aria-pressed={active} onClick={()=>Active(!active)} onKeyDown={e=>{if(e.key==='Escape')Active(false);if(active&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();position.current.x=Math.max(0,Math.min(100,position.current.x+(e.key==='ArrowRight'?10:e.key==='ArrowLeft'?-10:0)));position.current.y=Math.max(0,Math.min(100,position.current.y+(e.key==='ArrowDown'?10:e.key==='ArrowUp'?-10:0)));const jacket=ref.current?.closest<HTMLElement>('.dossier-jacket');jacket?.style.setProperty('--lamp-x',position.current.x+'%');jacket?.style.setProperty('--lamp-y',position.current.y+'%')}}}>{active?'Rallumer la pièce':'Examiner à la lampe'}</button>{active&&<p>Déplacez la lumière avec la souris, le doigt ou les touches fléchées.</p>}</div>}
export function Ghost404(){return <section className="ghost-page"><p className="eyebrow">ARCHIVES ERPI / PIÈCE MANQUANTE</p><div className="ghost-code"><span>4</span><Ghost size={130} strokeWidth={1}/><span>4</span></div><h1>Cette page nous a<br/>fait un ghosting.</h1><p>On lui a demandé un signe.<br/>Elle nous a répondu « page introuvable ».</p><div className="actions"><Link className="button primary" href="/dossiers">Reprendre l’enquête <ArrowRight size={17}/></Link><Link className="button" href="/">Retour en lieu sûr</Link><Link className="textlink" href="/recherche">Rechercher une piste</Link></div><p className="small">Hypothèse retenue : adresse erronée ou page déplacée.<br/>Le fantôme bénéficie de la présomption d’innocence.</p></section>}
export function AppointmentCTA(){return <section className="appointment-callout"><div><p className="eyebrow">RENDEZ-VOUS</p><h2>Parlons de vos observations.</h2><p>Choisissez un entretien téléphonique ou une visio pour préparer votre demande.</p></div><Link className="button primary" href="/rendez-vous"><CalendarDays size={19}/>Prendre rendez-vous</Link></section>}
export function SocialLinks(){return <section className="social-section"><div className="sectionhead"><div><p className="eyebrow">YOUTUBE & TIKTOK</p><h2>Les vidéos ERPI</h2></div><Link className="textlink" href="/medias">Les reportages →</Link></div><div className="social-grid"><a className="social-card" href="https://www.tiktok.com/@erpi_paranormal" target="_blank" rel="noreferrer"><img src="/brands/tiktok.svg" alt="" width="35" height="35"/><div><span className="eyebrow">TIKTOK</span><h3>@erpi_paranormal</h3><p>Retrouvez les formats courts du compte ERPI Paranormal.</p></div><span></span></a><a className="social-card" href="https://www.youtube.com/@erpiparanormal9160" target="_blank" rel="noreferrer"><img src="/brands/youtube.svg" alt="" width="39" height="39"/><div><span className="eyebrow">YOUTUBE</span><h3>ERPI Paranormal</h3><p>Les enquêtes et les vidéos de la chaîne ERPI Paranormal.</p></div><span></span></a></div><p className="small">Retrouvez ERPI sur TikTok et YouTube. Les liens ouvrent directement les plateformes.</p></section>}
