'use client';
import Link from './navigation';
import {Newsroom} from './newsroom';
import {HomeScene} from './home-scene';
import {ProductVisual} from './product-visual';
import {articles} from './editorial-data';
export function EditorialHome(){return <div className="cinema-home">
<HomeScene/><nav className="home-public-paths" aria-label="Commencer la visite"><Link href="/erpi">Découvrir ERPI</Link><Link href="/dossiers">Consulter les enquêtes</Link><Link href="/interventions">Un phénomène chez vous ?</Link></nav>
<Newsroom/>
<section className="home-method"><p className="chapter-label">L’ESPRIT DE L’ENQUÊTE</p><h2>Prendre les témoignages au sérieux.<br/><em>Garder l’esprit critique.</em></h2><div><p>Écouter, observer, confronter les hypothèses. Explorer l’inexpliqué demande de la curiosité, mais aussi du recul.</p><Link className="editorial-link" href="/erpi">Découvrir notre démarche →</Link></div></section>

<section className="cinema-journal"><div><p className="chapter-label">LE JOURNAL DE L’ENQUÊTEUR</p><h2>Avant de tirer<br/>des conclusions.</h2><Link className="editorial-link" href="/actualites">Lire le journal <span>→</span></Link></div><div className="journal-notes">{articles.slice(0,2).map(a=><Link href={'/actualites/'+a.id} key={a.id}><p className="chapter-label">{a.category}</p><h3>{a.title}</h3><p>{a.intro}</p><span className="subtle-link">Lire l’article →</span></Link>)}</div></section>

<section className="home-preparation-offers"><div><p className="chapter-label">LA SÉLECTION ERPI</p><h2>Préparer le terrain.</h2><Link className="editorial-link" href="/boutique">Toute la boutique →</Link></div><Link href="/boutique/kit-debutant"><ProductVisual id="kit-debutant" title="Kit découverte"/><h3>Votre première sortie commence ici.</h3><p>Kit découverte · 59 €</p></Link><Link href="/rendez-vous"><img src="/course-audio.jpg" alt="Illustration d’un poste d’analyse audio"/><h3>Un regard sur vos observations.</h3><p>Visio d’analyse · 45 minutes · 55 €</p></Link></section><section className="witness-note"><div><h2>Et si cela se passe chez vous ?</h2><p>Commencez par nous raconter les faits. L’entretien, le signalement et l’éventuelle intervention font partie d’une même démarche.</p></div><Link className="button" href="/interventions">Comment contacter l’équipe →</Link></section>
<section className="cinema-letter home-follow"><div><p className="chapter-label">RESTER DANS LA BOUCLE</p><h2>L’enquête continue.</h2><p>Vidéos, coulisses et nouvelles de l’équipe : retrouvez ERPI entre deux visites.</p></div><div><a href="https://www.youtube.com/@erpiparanormal9160" target="_blank" rel="noreferrer"><img src="/brands/youtube.svg" width={26} height={26} alt=""/>Suivre ERPI sur YouTube</a><a href="https://www.tiktok.com/@erpi_paranormal" target="_blank" rel="noreferrer"><img src="/brands/tiktok.svg" width={24} height={24} alt=""/>Retrouver ERPI sur TikTok</a></div></section>
</div>}
export function ParticipatePage(){return <div className="participate-page"><section className="pagetitle"><p className="breadcrumbs"><Link href="/">Accueil</Link><span>/</span>Participer</p><p className="chapter-label">VIVRE L’EXPÉRIENCE ERPI</p><h1>Votre première<br/>nuit commence ici.</h1><p className="lead">Vous souhaitez découvrir l’enquête sur le terrain ou apprendre à mener vos propres observations ? Deux façons de commencer.</p></section><section className="participate-feature"><img src="/course-terrain.jpg" alt="Illustration d’un carnet et du matériel d’observation" width={1536} height={1024}/><div><p className="chapter-label">AVEC L’ÉQUIPE</p><h2>Participer à une sortie.</h2><p>Nuits d’enquête, rencontres et ateliers. Retrouvez les dates, les lieux, les conditions et les places disponibles dans l’agenda.</p><Link className="button primary" href="/evenements">Voir les sorties & réserver →</Link></div></section><section className="learning-path"><div><p className="chapter-label">À VOTRE RYTHME</p><h2>Apprendre la méthode.</h2><p>Deux formations guidées : préparer une investigation et examiner un enregistrement audio. Chaque parcours comprend des exercices et des corrigés.</p><Link className="button" href="/formations">Découvrir les formations →</Link></div><div className="continued-path"><p className="chapter-label">POUR ALLER PLUS LOIN</p><Link href="/academie">Commencer par les ressources gratuites <span>→</span></Link><Link href="/communaute">Rejoindre la communauté <span>→</span></Link><Link href="/professionnels">Organiser une expérience pour un groupe <span>→</span></Link></div></section></div>}
