'use client';
import type {ReactNode} from 'react';
import Link from './navigation';
import {Newsroom} from './newsroom';
import {dossiers} from './data';
import {articles} from './editorial-data';
export function EditorialHome({newsletter}:{newsletter:ReactNode}){return <div className="cinema-home">
<Newsroom/>
<section className="cinema-archives"><div className="chapter-heading"><div><p className="chapter-label">01 / COMPRENDRE</p><h2>À l’intérieur<br/>d’une enquête.</h2></div><p>Ce qui a été rapporté. Ce qui a été observé. Les hypothèses retenues — et les questions qui restent.</p></div><p className="sample-caption">Les dossiers ci-dessous sont des exemples pédagogiques fictifs.</p><div className="cinema-records">{dossiers.slice(0,2).map((d,i)=><Link key={d.id} href={'/dossiers/'+d.id}><span className="file-no">{String(i+1).padStart(2,'0')}</span><div><p className="file-meta">{d.region} · {d.type}</p><h3>{d.title}</h3><p className="file-status">{d.status}</p></div><span className="file-arrow" aria-hidden="true"></span></Link>)}</div><Link className="editorial-link" href="/dossiers">Ouvrir les archives <span>→</span></Link></section>
<section className="cinema-experience"><figure><img src="/course-terrain.jpg" alt="Carnet et matériel préparés pour une observation — illustration" loading="lazy" width={1536} height={1024}/><figcaption>Avant de partir, préparer son regard. Illustration.</figcaption></figure><div className="experience-copy"><p className="chapter-label">02 / VIVRE L’EXPÉRIENCE</p><h2>De l’écran<br/>au terrain.</h2><p>Participer à une sortie accompagnée ou apprendre les bases de l’investigation. Choisissez la façon dont vous souhaitez commencer.</p><Link className="button primary" href="/participer">Trouver mon expérience <span>→</span></Link><p className="experience-note">Sorties d’enquête · Ateliers · Formations</p></div></section>
<section className="cinema-journal"><div><p className="chapter-label">LE JOURNAL DE L’ENQUÊTEUR</p><h2>Avant de tirer<br/>des conclusions.</h2><Link className="editorial-link" href="/actualites">Lire le journal <span>→</span></Link></div><div className="journal-notes">{articles.slice(0,2).map(a=><Link href={'/actualites/'+a.id} key={a.id}><p className="chapter-label">{a.category}</p><h3>{a.title}</h3><p>{a.intro}</p><span className="subtle-link">Lire l’article →</span></Link>)}</div></section>
<section className="equipment-note"><p className="chapter-label">03 / S’ÉQUIPER</p><div><h2>Le bon outil.<br/>Pas une preuve.</h2><p>Découvrez ce que mesure chaque appareil, ses limites et les kits pour débuter.</p></div><Link className="editorial-link" href="/boutique">Explorer la boutique <span>→</span></Link></section>
<section className="witness-note"><div><h2>Et si cela se passe chez vous ?</h2><p>Commencez par nous raconter les faits. L’entretien, le signalement et l’éventuelle intervention font partie d’une même démarche.</p></div><Link className="button" href="/interventions">Comment contacter l’équipe →</Link></section>
<section className="cinema-letter"><div><p className="chapter-label">LA LETTRE ERPI</p><h2>La suite,<br/>au prochain dossier.</h2><p>Les nouvelles enquêtes, les publications et les rendez-vous de l’association.</p></div>{newsletter}</section>
</div>}
export function ParticipatePage(){return <div className="participate-page"><section className="pagetitle"><p className="breadcrumbs"><Link href="/">Accueil</Link><span>/</span>Participer</p><p className="chapter-label">VIVRE L’EXPÉRIENCE ERPI</p><h1>Votre première<br/>nuit commence ici.</h1><p className="lead">Vous souhaitez découvrir l’enquête sur le terrain ou apprendre à mener vos propres observations ? Deux façons de commencer.</p></section><section className="participate-feature"><img src="/course-terrain.jpg" alt="Illustration d’un carnet et du matériel d’observation" width={1536} height={1024}/><div><p className="chapter-label">AVEC L’ÉQUIPE</p><h2>Participer à une sortie.</h2><p>Nuits d’enquête, rencontres et ateliers. Retrouvez les dates, les lieux, les conditions et les places disponibles dans l’agenda.</p><Link className="button primary" href="/evenements">Voir les sorties & réserver →</Link></div></section><section className="learning-path"><div><p className="chapter-label">À VOTRE RYTHME</p><h2>Apprendre la méthode.</h2><p>Deux formations guidées : préparer une investigation et examiner un enregistrement audio. Chaque parcours comprend des exercices et des corrigés.</p><Link className="button" href="/formations">Découvrir les formations →</Link></div><div className="continued-path"><p className="chapter-label">POUR ALLER PLUS LOIN</p><Link href="/academie">Commencer par les ressources gratuites <span>→</span></Link><Link href="/communaute">Rejoindre la communauté <span>→</span></Link><Link href="/professionnels">Organiser une expérience pour un groupe <span>→</span></Link></div></section></div>}
