'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Menu,X,Search,ShoppingBag,UserRound,ChevronDown} from 'lucide-react';
import Link,{usePathname} from './navigation';
const groups=[
 {name:'ERPI Paranormal',intro:'Les enquêtes, l’équipe et ses publications.',links:[['ERPI & sa méthode','/erpi'],['Dossiers d’enquête','/dossiers'],['Carte des enquêtes','/carte'],['Vidéos · YouTube & TikTok','/videos'],['Le journal','/actualites'],['Dans les médias','/medias']]},
 {name:'Faire appel à ERPI',intro:'Du premier échange à l’intervention.',links:[['Prendre rendez-vous','/rendez-vous'],['Un phénomène chez vous ?','/interventions'],['Signaler un phénomène','/signaler'],['Lieux & professionnels','/professionnels'],['Contacter l’équipe','/contact']]},
 {name:'Communauté',intro:'Se rencontrer et apprendre.',links:[['La communauté ERPI','/communaute'],['Formations','/formations'],['Sorties & rencontres','/evenements'],['Guides gratuits','/academie'],['Urbex & nature','/urbex']]},
 {name:'Boutique & outils',intro:'S’équiper sur le terrain et organiser ses observations.',links:[['La boutique','/boutique'],['Guide du matériel','/materiel'],['Applications ERPI','/applications']]}
];
export function JourneyHeader({cartCount}:{cartCount:number}){
 const path=usePathname();const[mobile,Mobile]=useState(false);const root=useRef<HTMLElement>(null);
 const close=useCallback(()=>{Mobile(false);root.current?.querySelectorAll('details').forEach(d=>d.open=false)},[]);
 useEffect(()=>{close()},[path,close]);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(root.current&&!root.current.contains(e.target as Node))close()};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){const focused=root.current?.querySelector<HTMLDetailsElement>('details[open]');const toggle=root.current?.querySelector<HTMLButtonElement>('.mobile-menu');if(toggle?.offsetParent)toggle.focus();else focused?.querySelector<HTMLElement>('summary')?.focus();close()}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[close]);
 return <><a className="skip" href="#main">Aller au contenu</a><header ref={root} className="sitehead journey-header"><Link href="/" className="brand" aria-label="ERPI Paranormal accueil">ERP<b className="neon-i">I</b><span>PARANORMAL</span></Link><button className="mobile-menu" onClick={()=>Mobile(!mobile)} aria-expanded={mobile} aria-controls="journey-navigation">{mobile?<X size={21}/>:<Menu size={21}/>}<span>{mobile?'Fermer':'Menu'}</span></button><nav id="journey-navigation" className={mobile?'is-open':''} aria-label="Navigation principale">{groups.map(g=><details key={g.name} name="journey-menu" className="nav-group"><summary className={g.links.some(([,url])=>path===url||path.startsWith(url+'/'))?'is-current':''}>{g.name}<ChevronDown size={13}/></summary><div className="nav-dropdown"><p>{g.intro}</p>{g.links.map(([label,url])=><Link key={url} href={url} onClick={close} aria-current={path===url?'page':undefined}>{label}</Link>)}</div></details>)}</nav><div className="headtools"><Link aria-label="Rechercher" href="/recherche"><Search size={19}/></Link><Link aria-label="Mon compte" href="/compte"><UserRound size={19}/></Link><Link aria-label={`Panier, ${cartCount} articles`} href="/panier"><ShoppingBag size={19}/>{cartCount>0&&<span>{cartCount}</span>}</Link></div></header></>
}
