import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {youtubeChannel,videoFallback,type NewsItem} from './news-data';
export function newsDb(){if(!env.DB)throw new Error('News storage unavailable');return env.DB;}
export async function isNewsEditor(){const user=await getChatGPTUser();const allowed=env.ERPI_EDITOR_EMAIL?.toLowerCase().trim();return user&&allowed&&user.email.toLowerCase()===allowed?user:null;}
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)));
export async function youtubeNews(){let cached:{payload:string;checked_at:number}|null=null;try{cached=await newsDb().prepare('SELECT payload, checked_at FROM erpi_feed_cache WHERE key = ?').bind('youtube').first();if(cached&&Date.now()-cached.checked_at<300000)return{items:JSON.parse(cached.payload) as NewsItem[],state:'synced',checkedAt:cached.checked_at};}catch{/* A verified snapshot remains available if storage is unavailable. */}
 try{const response=await fetch('https://www.youtube.com/feeds/videos.xml?channel_id='+youtubeChannel,{signal:AbortSignal.timeout(7000)});if(!response.ok)throw new Error('YouTube feed unavailable');const xml=await response.text();if(xml.length>1000000)throw new Error('Unexpected feed size');const items:NewsItem[]=[...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].flatMap(([,entry])=>{const id=entry.match(/<yt:videoId>([^<]+)</)?.[1];const title=entry.match(/<title>([\s\S]*?)<\/title>/)?.[1];const publishedAt=entry.match(/<published>([^<]+)</)?.[1];const thumb=entry.match(/<media:thumbnail[^>]+url="([^"]+)"/)?.[1];if(!id||!/^[\w-]{11}$/.test(id)||!title||!publishedAt||!Number.isFinite(Date.parse(publishedAt)))return[];return[{id:'yt-'+id,videoId:id,title:decode(title),publishedAt,kind:'YouTube',url:'https://www.youtube.com/watch?v='+id,summary:'Une publication de la chaîne ERPI Paranormal.',thumbnail:thumb&&/^https:\/\/i[0-9]?\.ytimg\.com\//.test(thumb)?decode(thumb):undefined}];});if(!items.length)throw new Error('Empty feed');const checkedAt=Date.now();try{await newsDb().prepare('INSERT INTO erpi_feed_cache (key,payload,checked_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET payload=excluded.payload,checked_at=excluded.checked_at').bind('youtube',JSON.stringify(items),checkedAt).run();}catch{/* The fetched feed is still usable. */}return{items,state:'synced',checkedAt};
 }catch(error){console.warn('ERPI YouTube feed:',error instanceof Error?error.message:'unavailable');return{items:cached?JSON.parse(cached.payload) as NewsItem[]:videoFallback,state:'cached',checkedAt:cached?.checked_at||null};}}
export const selectNews='SELECT id,title,summary,kind,url,published_at AS publishedAt,expires_at AS expiresAt,status,pinned FROM erpi_announcements';
