'use client';
import {useEffect,useState} from 'react';
import {Play,Radio,Newspaper} from 'lucide-react';
import Link from './navigation';
import {videoFallback,pressFallback,visibleNews,isRecent,newsKinds,type NewsItem} from './news-data';
const dated=(s:string)=>new Date(s).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Paris'});
function NewsLink({item,children,className}:{item:NewsItem;children:React.ReactNode;className?:string}){return <Link className={className} href={item.url} {...(item.url.startsWith('https://')?{target:'_blank',rel:'noopener noreferrer'}:{})}>{children}</Link>}
export function Newsroom(){const[items,Items]=useState<NewsItem[]>(visibleNews([...videoFallback,...pressFallback]));const[kind,Kind]=useState('Tout');const[playing,Playing]=useState(false);const[stale,Stale]=useState(false);
 useEffect(()=>{let controller:AbortController|null=null;const refresh=async()=>{controller?.abort();controller=new AbortController();try{const r=await fetch('/api/news',{signal:controller.signal});if(!r.ok)throw new Error();const data=await r.json();if(Array.isArray(data.items)&&data.items.length){Items(data.items);Stale(data.youtube==='cached'||!data.editorialAvailable)}}catch(e){if((e as Error).name!=='AbortError')Stale(true)}};void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh()},60000);const visible=()=>{if(!document.hidden)void refresh()};document.addEventListener('visibilitychange',visible);window.addEventListener('erpi:news',visible);return()=>{controller?.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible);window.removeEventListener('erpi:news',visible)}},[]);
 const filtered=items.filter(i=>kind==='Tout'||i.kind===kind);const lead=filtered[0];useEffect(()=>{Playing(false)},[lead?.id]);
 return <section className="newsroom"><header className="news-masthead"><div><p className="chapter-label">VIDÉOS · SORTIES · JOURNAL · ANNONCES</p><h2>Dernières nouvelles.</h2></div><p>Ce qui se passe.<br/>Ce qui reste à découvrir.</p></header><nav className="news-filter" aria-label="Filtrer les actualités">{['Tout',...newsKinds].map(k=><button key={k} onClick={()=>Kind(k)} aria-pressed={kind===k}>{k}</button>)}</nav>{lead?<><article className={'news-lead '+(lead.videoId?'has-video':'')} key={lead.id}><div className="news-lead-copy"><p className="news-overline"><span>{lead.pinned?'À LA UNE':isRecent(lead)?'EN CE MOMENT':'À REVOIR & À LIRE'}</span><span>{lead.kind}</span></p><h3>{lead.title}</h3><time dateTime={lead.publishedAt}>{dated(lead.publishedAt)}</time><p>{lead.summary}</p><NewsLink className="button primary" item={lead}>{lead.kind==='YouTube'||lead.kind==='TikTok'?'Voir la vidéo':lead.kind==='Sortie'?'Découvrir la sortie':'Lire la publication'}</NewsLink></div><div className="news-screen">{playing&&lead.videoId?<iframe src={'https://www.youtube-nocookie.com/embed/'+lead.videoId+'?autoplay=1'} title={lead.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:lead.videoId?<button className="video-poster" onClick={()=>Playing(true)} aria-label={'Lire la vidéo : '+lead.title}>{lead.thumbnail&&<img src={lead.thumbnail} alt="" width={480} height={360}/>}<span className="screen-play"><Play size={30} fill="currentColor"/><span>REGARDER</span></span><span className="screen-caption">ERPI PARANORMAL / YOUTUBE</span></button>:<div className="announcement-screen"><span className="announcement-index">ERPI</span><Newspaper size={52} strokeWidth={1}/><span>{lead.kind.toUpperCase()}</span></div>}</div></article>{stale&&<p className="feed-status">Dernières publications disponibles.</p>}</>:<div className="news-empty"><Radio size={28}/><h2>{kind==='TikTok'?'ERPI est aussi sur TikTok.':'Pas d’annonce publiée dans cette rubrique.'}</h2><p>{kind==='TikTok'?'Retrouvez les formats courts directement sur le compte ERPI Paranormal.':'Les prochaines publications apparaîtront ici. En attendant, retrouvez les vidéos et les articles du fil.'}</p>{kind==='TikTok'?<a className="button" href="https://www.tiktok.com/@erpi_paranormal" target="_blank" rel="noreferrer">Ouvrir TikTok</a>:<button className="button" onClick={()=>Kind('Tout')}>Revenir au fil</button>}</div>}<div className="news-platforms"><span>Retrouver ERPI</span><a href="https://www.youtube.com/@erpiparanormal9160" target="_blank" rel="noreferrer"><img src="/brands/youtube.svg" alt="" width={22} height={22}/>YouTube</a><a href="https://www.tiktok.com/@erpi_paranormal" target="_blank" rel="noreferrer"><img src="/brands/tiktok.svg" alt="" width={20} height={20}/>TikTok</a><Link href="/medias">Les publications dans la presse</Link></div></section>
}
