'use client';
import {useEffect,useRef,useState} from 'react';
import Link from './navigation';
const rooms=[
 {name:'Le bureau',image:'/office-desk.jpg',position:'62% 64%',title:'Faire la lumière',end:'sur l’inexpliqué.',text:'Un bruit. Une présence. Une question. L’enquête commence par les faits : écouter, observer, documenter.',links:[['Consulter les enquêtes','/dossiers'],['Découvrir ERPI','/erpi']]},
 {name:'Les lieux',image:'/office-desk.jpg',position:'65% 16%',title:'Chaque lieu',end:'a son histoire.',text:'Relier les observations à leur contexte. Retrouver les lieux et les enquêtes documentés, sans exposer les adresses confidentielles.',links:[['Explorer la carte','/carte']]},
 {name:'Les archives',image:'/office-archives.jpg',position:'24% 66%',title:'Garder une trace.',end:'Croiser les regards.',text:'Reportages, entretiens, archives. Lire ce qui a été publié sur ERPI, avec les dates et les sources.',links:[['Parcourir les médias','/medias']]},
 {name:'Les témoignages',image:'/office-archives.jpg',position:'86% 42%',title:'Et si cela',end:'se passe chez vous ?',text:'Racontez-nous ce que vous avez observé. Un premier échange confidentiel, sans promesse de réponse et sans conclusion précipitée.',links:[['Un phénomène chez vous ?','/interventions'],['Prendre rendez-vous','/rendez-vous']]},
 {name:'Le terrain',image:'/office-field.jpg',position:'22% 70%',title:'Préparer le terrain.',end:'Apprendre à observer.',text:'Comprendre les instruments, connaître leurs limites et construire une méthode. Le matériel accompagne l’enquête ; il ne remplace pas le regard critique.',links:[['Explorer la boutique','/boutique'],['Découvrir les formations','/formations']]},
 {name:'La projection',image:'/office-field.jpg',position:'86% 32%',title:'L’enquête continue.',end:'Au-delà de ce bureau.',text:'Les enquêtes en images, les coulisses et les échanges. Retrouvez ERPI entre deux visites.',links:[['YouTube','https://www.youtube.com/@erpiparanormal9160'],['TikTok','https://www.tiktok.com/@erpi_paranormal'],['La communauté','/communaute']]},
];
export function OfficeJourney(){
 const root=useRef<HTMLElement>(null);const stage=useRef<HTMLDivElement>(null);const photos=useRef<(HTMLDivElement|null)[]>([]);const chapters=useRef<(HTMLElement|null)[]>([]);const [enhanced,Enhanced]=useState(false);const[active,Active]=useState(0);const activeRef=useRef(0);
 useEffect(()=>{const size=matchMedia('(min-width: 850px) and (min-height: 620px)'),motion=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>Enhanced(size.matches&&!motion.matches&&document.documentElement.dataset.motion!=='off');const observer=new MutationObserver(change);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-motion']});size.addEventListener('change',change);motion.addEventListener('change',change);change();return()=>{observer.disconnect();size.removeEventListener('change',change);motion.removeEventListener('change',change)}},[]);
 useEffect(()=>{if(!enhanced)return;let frame=0;const update=()=>{frame=0;if(!root.current||!stage.current)return;const height=stage.current.clientHeight;const rect=root.current.getBoundingClientRect();const header=document.querySelector('.sitehead')?.getBoundingClientRect().height||96;const p=Math.max(0,Math.min(5,(header-rect.top)/height));const index=Math.min(5,Math.floor(p+.5));if(index!==activeRef.current){activeRef.current=index;Active(index)}photos.current.forEach((photo,i)=>{if(!photo)return;const local=Math.max(-.5,Math.min(.5,p-i));const zoom=i%2===0?1.04:1.24;photo.style.transform=`perspective(1400px) translate3d(${(i%2===0?-1:1)*local*22}px,${-local*14}px,${local*40}px) rotateY(${local*.8}deg) scale(${zoom+local*.055})`});};const request=()=>{if(!frame)frame=requestAnimationFrame(update)};window.addEventListener('scroll',request,{passive:true});window.addEventListener('resize',request);request();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',request);window.removeEventListener('resize',request)}},[enhanced]);
 function go(index:number){const el=chapters.current[index];if(!el)return;el.scrollIntoView({behavior:enhanced?'smooth':'auto',block:'start'});el.focus({preventScroll:true})}
 return <section ref={root} className="office-journey" data-shot={active} data-scroll={enhanced?'true':'false'} aria-label="Traverser le bureau d’enquête ERPI">
  <div className="office-stage" ref={stage} aria-hidden="true"><div className="office-camera">{enhanced&&rooms.map((room,i)=><div className={'office-view '+(active===i?'is-current':'')} ref={node=>{photos.current[i]=node}} key={room.name}><img src={room.image} alt="" style={{objectPosition:room.position}} width={1672} height={941} decoding="async"/></div>)}</div><div className="office-shade"/><div className="office-halo"/><div className="office-dust">{Array.from({length:9},(_,i)=><i key={i} style={{left:`${35+i*6}%`,top:`${12+(i*19)%65}%`,animationDelay:`-${i*2}s`}}/>)}</div></div>
  <div className="office-script">{rooms.map((room,i)=><section id={'office-chapter-'+i} ref={node=>{chapters.current[i]=node}} className="office-chapter" key={room.name} tabIndex={-1} aria-labelledby={'office-title-'+i}>
   <img className="office-mobile-image" src={room.image} alt="" style={{objectPosition:room.position}} loading={i===0?'eager':'lazy'} width={1672} height={941}/>
   <div className="office-copy"><p className="office-caption">{String(i+1).padStart(2,'0')} / {room.name} <span>ERPI PARANORMAL</span></p>{i===0?<h1 id={'office-title-'+i}>{room.title}<br/><em>{room.end}</em></h1>:<h2 id={'office-title-'+i}>{room.title}<br/><em>{room.end}</em></h2>}<p className="office-description">{room.text}</p><div className="office-actions">{room.links.map(([label,href],j)=><Link key={href} href={href} className={j===0?'button primary':'office-link'} {...(href.startsWith('https')?{target:'_blank',rel:'noreferrer'}:{})}>{label}</Link>)}</div>{i===0&&<div className="office-introduction"><span className="office-scroll-hint">Faites défiler pour traverser le bureau</span><a href="#home-news">Accéder aux dernières nouvelles</a></div>}</div>
  </section>)}</div>
  {enhanced&&<nav className="office-chapters" aria-label="Choisir une zone du bureau"><span>{String(active+1).padStart(2,'0')} / 06 — {rooms[active].name}</span><div>{rooms.map((room,i)=><button key={room.name} onClick={()=>go(i)} aria-current={active===i?'step':undefined} aria-label={'Aller à la zone '+(i+1)+' : '+room.name}>{String(i+1).padStart(2,'0')}</button>)}</div><a href="#home-news">Dernières nouvelles</a></nav>}
  <p className="office-credit">Un décor illustratif pour découvrir ERPI. Les dossiers et les sources sont accessibles dans chaque rubrique.</p>
 </section>
}
