import {sourceLinks} from './data';
export const referenceLinks=[
{category:'Presse',publisher:'DNA',title:sourceLinks[0].title,url:sourceLinks[0].url,detail:'18 août 2021 · Reportage au Schwarzenbourg avec Nicolas Vora, présenté comme ancien militaire. Article payant : consultation sur le site du média.'},
{category:'Presse',publisher:'HelloMonaco',title:sourceLinks[1].title,url:sourceLinks[1].url,detail:'16 novembre 2016 · Portrait de Nicolas Vora et Romain Gorlez, à Nice. Les méthodes et la gratuité évoquées décrivent cette période, pas une offre actuelle.'},
{category:'Association',publisher:'Net1901',title:'ERPI Paranormal · RNA W062010565',url:'https://www.net1901.org/association/ERPI-PARANORMAL%2C1857376.html',detail:'Déclaration de création le 20 février 2017, publication le 4 mars 2017 selon la fiche. Implantation à Tourrette-Levens et objet déclaré. Les dates administratives doivent être distinguées du début de l’activité relaté dans la presse.'},
{category:'Association',publisher:'Annuaire-Mairie',title:'Répertoire des associations de Tourrette-Levens',url:'https://www.annuaire-mairie.fr/association-tourrette-levens.html',detail:'Référence le même numéro RNA W062010565. Annuaire indépendant, distinct de l’administration municipale ; il ne constitue pas une seconde déclaration officielle.'},
{category:'Association',publisher:'Kananas',title:'Objet déclaré de l’association',url:'https://www.kananas.com/association/fiche/70578/erpi-paranormal.html',detail:'Reprend l’objet associatif : investigations, tests, enquêtes et rapports, avec recherche d’explications rationnelles. Déclaration d’intention, et non validation scientifique des résultats.'},
{category:'Piste à vérifier',publisher:'TheBookEdition',title:'Page auteur au nom de Nicolas Vora',url:'https://www.thebookedition.com/fr/31545_nicolas-vora',detail:'Piste biographique fournie pour vérification. Le rattachement de cette page au Nicolas Vora d’ERPI reste à confirmer avant d’attribuer une œuvre ou une activité d’auteur.'},
{category:'Réseaux',publisher:'TikBuddy',title:'Profil référencé @erpi_paranormal',url:'https://tikbuddy.com/tiktok/erpi_paranormal',detail:'Annuaire tiers référençant le compte TikTok et mentionnant Facebook et YouTube dans sa biographie. Aucun chiffre d’abonnés ou de vues n’est repris.'}
];
export function ReferenceLibrary(){return <section className="space"><div className="sectionhead"><div><p className="eyebrow">LES SOURCES / REPÈRES DOCUMENTAIRES</p><h2>Remonter à l’origine.</h2></div></div><p>Reportages, archives associatives et liens de référence. Les publications historiques ne décrivent pas nécessairement l’activité actuelle d’ERPI.</p><div className="grid3">{referenceLinks.map(r=><article className="panel" key={r.url}><span className="badge">{r.category}</span><p className="eyebrow space-sm">{r.publisher}</p><h3>{r.title}</h3><p>{r.detail}</p><a className="textlink" href={r.url} target="_blank" rel="noreferrer">Consulter la référence </a></article>)}</div><p className="small space-sm">Les annuaires peuvent reprendre la même déclaration : leur concordance ne garantit pas une vérification indépendante. Les textes de presse ne sont pas reproduits ici.</p></section>}
