import 'server-only';
import {cookies} from 'next/headers';
import type {NewsItem} from './news-data';
export function settings(){const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SECRET_KEY; if(!url||!key)throw new Error('Supabase is not configured');return {url,key};}
export async function supabase(path:string,init:RequestInit={}){const {url,key}=settings();const response=await fetch(url+path,{...init,cache:'no-store',headers:{apikey:key,'Content-Type':'application/json',...init.headers},signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('Supabase request failed: '+response.status);const body = await response.text();
  return body ? JSON.parse(body) : null;}
export async function isNewsEditor(){const token=(await cookies()).get('erpi_admin_session')?.value;if(!token)return null;try{const user=await supabase('/auth/v1/user',{headers:{Authorization:'Bearer '+token}});const allowed=process.env.ERPI_EDITOR_EMAIL?.trim().toLowerCase();return allowed&&user.email_confirmed_at&&user.email?.toLowerCase()===allowed?{userId:user.id,email:user.email}:null;}catch{return null;}}
export async function listAnnouncements(admin=false):Promise<NewsItem[]>{if(admin&&!await isNewsEditor())throw new Error('Forbidden');const now=new Date().toISOString();const q=new URLSearchParams({select:'id,title,summary,kind,url,publishedAt:published_at,expiresAt:expires_at,status,pinned',order:admin?'updated_at.desc':'pinned.desc,published_at.desc',limit:admin?'200':'100'});if(!admin){q.set('status','eq.published');q.set('published_at','lte.'+now);q.set('or','(expires_at.is.null,expires_at.gt.'+now+')');}return supabase('/rest/v1/erpi_announcements?'+q);}
export async function saveAnnouncement(value:Record<string,unknown>){if(!await isNewsEditor())throw new Error('Forbidden');return supabase('/rest/v1/erpi_announcements?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(value)});}
export async function getFeedCache(){const rows=await supabase('/rest/v1/erpi_feed_cache?key=eq.youtube&select=payload,checked_at&limit=1');return rows[0]||null;}
export async function setFeedCache(payload:string,checked_at:number){return supabase('/rest/v1/erpi_feed_cache?on_conflict=key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:'youtube',payload,checked_at})});}
